import traceback
import scrapy, datetime, os, json, re
import mysql.connector

# filter_date = "20.02.2021" # type is dd.mm.yyyy
location_list = [
    "Stuttgart",
    "Berlin",
    "Ansbach",
    "Aschaffenburg",
    "Augsburg",
    "Bamberg",
    "Bayreuth",
    "Coburg",
    "Erlangen",
    "Fürth",
    "Hof",
    "Ingolstadt",
    "Kaufbeuren",
    "Kempten (Allgäu)",
    "Landshut",
    "Memmingen",
    "München Landeshauptstadt",
    "Nürnberg",
    "Passau",
    "Regensburg",
    "Rosenheim",
    "Schwabach",
    "Schweinfurt",
    "Straubing",
    "Weiden in der Oberpfalz",
    "Würzburg",
    "Bad Kissingen",
    "Bad Reichenhall",
    "Dachau",
    "Deggendorf",
    "Dillingen an der Donau",
    "Dinkelsbühl",
    "Donauwörth",
    "Eichstätt",
    "Erding",
    "Forchheim",
    "Freising",
    "Fürstenfeldbruck",
    "Germering",
    "Günzburg",
    "Kitzingen",
    "Kulmbach",
    "Landsberg am Lech",
    "Lindau (Bodensee)",
    "Marktredwitz",
    "Neuburg an der Donau",
    "Neumarkt in der Oberpfalz",
    "Neustadt bei Coburg",
    "Neu-Ulm",
    "Nördlingen",
    "Rothenburg ob der Tauber",
    "Schwandorf",
    "Selb",
    "Traunstein",
    "Weißenburg in Bayern",
    "Abenberg",
    "Abensberg",
    "Absberg Markt",
    "Abtswind Markt",
    "Achslach",
    "Adelschlag",
    "Adelsdorf",
    "Adelshofen (Mittelfranken)",
    "Adelshofen (Oberbayern)",
    "Adelsried",
    "Adelzhausen",
    "Adlkofen",
    "Affing",
    "Aham",
    "Aholfing",
    "Aholming",
    "Ahorn",
    "Ahorntal",
    "Aicha vorm Wald",
    "Aichach",
    "Aichen",
    "Aidenbach Markt",
    "Aidhausen",
    "Aiglsbach",
    "Aindling Markt",
    "Ainring",
    "Aislingen Markt",
    "Aiterhofen",
    "Aitrang",
    "Albaching",
    "Albertshofen",
    "Aldersbach",
    "Alerheim",
    "Alesheim",
    "Aletshausen",
    "Alfeld",
    "Allersberg Markt",
    "Allershausen",
    "Alling",
    "Allmannshofen",
    "Altdorf (Niederbayern) Markt",
    "Altdorf bei Nürnberg",
    "Alteglofsheim",
    "Altenbuch",
    "Altendorf (Landkreis Bamberg, Oberfranken)",
    "Altendorf (Landkreis Schwandorf, Oberpfalz)",
    "Altenkunstadt",
    "Altenmarkt an der Alz",
    "Altenmünster",
    "Altenstadt (Iller) Markt",
    "Altenstadt (bei Schongau)",
    "Altenstadt an der Waldnaab",
    "Altenthann",
    "Altertheim",
    "Altfraunhofen",
    "Althegnenberg",
    "Altmannstein Markt",
    "Altomünster Markt",
    "Altötting",
    "Altusried Markt",
    "Alzenau",
    "Amberg (Oberpfalz)",
    "Amberg (Schwaben)",
    "Amerang",
    "Amerdingen",
    "Ammerndorf Markt",
    "Ammerthal",
    "Amorbach",
    "Ampfing",
    "Andechs",
    "Anger",
    "Ansbach",
    "Antdorf",
    "Anzing",
    "Apfeldorf",
    "Apfeltrach",
    "Arberg Markt",
    "Aresing",
    "Arnbruck",
    "Arnschwang",
    "Arnstein",
    "Arnstorf Markt",
    "Arrach",
    "Arzberg",
    "Asbach-Bäumenheim",
    "Ascha",
    "Aschaffenburg",
    "Aschau am Inn",
    "Aschau im Chiemgau",
    "Aschheim",
    "Aßling",
    "Attenhofen",
    "Attenkirchen",
    "Atting",
    "Au in der Hallertau Markt",
    "Aub",
    "Aubstadt",
    "Auerbach (Niederbayern)",
    "Auerbach in der Oberpfalz",
    "Aufhausen",
    "Aufseß",
    "Augsburg",
    "Auhausen",
    "Aura an der Saale",
    "Aura im Sinngrund",
    "Aurach",
    "Aurachtal",
    "Außernzell",
    "Aying",
    "Aystetten",
    "Baar (Schwaben)",
    "Baar-Ebenhausen",
    "Babenhausen Markt",
    "Babensham",
    "Bach an der Donau",
    "Bachhagel",
    "Bächingen an der Brenz",
    "Bad Abbach Markt",
    "Bad Aibling",
    "Bad Alexandersbad",
    "Bad Bayersoien",
    "Bad Berneck im Fichtelgebirge",
    "Bad Birnbach Markt",
    "Bad Bocklet Markt",
    "Bad Brückenau",
    "Bad Endorf Markt",
    "Bad Feilnbach",
    "Bad Füssing",
    "Bad Griesbach im Rottal",
    "Bad Grönenbach Markt",
    "Bad Heilbrunn",
    "Bad Hindelang Markt",
    "Bad Kissingen",
    "Bad Kohlgrub",
    "Bad Königshofen im Grabfeld",
    "Bad Kötzting",
    "Bad Neualbenreuth Markt",
    "Bad Neustadt an der Saale",
    "Bad Reichenhall",
    "Bad Rodach",
    "Bad Staffelstein",
    "Bad Steben Markt",
    "Bad Tölz",
    "Bad Wiessee",
    "Bad Windsheim",
    "Bad Wörishofen",
    "Baierbach",
    "Baierbrunn",
    "Baiern",
    "Baiersdorf",
    "Baisweil",
    "Balderschwang",
    "Balzhausen",
    "Bamberg",
    "Barbing",
    "Bärnau",
    "Bastheim",
    "Baudenbach Markt",
    "Baunach",
    "Bayerbach (Rottal-Inn)",
    "Bayerbach bei Ergoldsbach",
    "Bayerisch Eisenstein",
    "Bayerisch Gmain",
    "Bayreuth",
    "Bayrischzell",
    "Bechhofen Markt",
    "Bechtsrieth",
    "Beilngries",
    "Bellenberg",
    "Benediktbeuern",
    "Benningen",
    "Beratzhausen Markt",
    "Berching",
    "Berchtesgaden Markt",
    "Berg (Oberfranken)",
    "Berg (am Starnberger See)",
    "Berg bei Neumarkt in der Oberpfalz",
    "Berg im Gau",
    "Bergen (Chiemgau)",
    "Bergen (Mittelfranken)",
    "Bergheim",
    "Bergkirchen",
    "Berglern",
    "Bergrheinfeld",
    "Bergtheim",
    "Bernau am Chiemsee",
    "Bernbeuren",
    "Berngau",
    "Bernhardswald",
    "Bernried am Starnberger See",
    "Bernried",
    "Bessenbach",
    "Betzenstein",
    "Betzigau",
    "Beutelsbach",
    "Biberbach Markt",
    "Bibertal",
    "Biburg",
    "Bichl",
    "Bidingen",
    "Biebelried",
    "Bieberehren",
    "Biessenhofen",
    "Bindlach",
    "Binswangen",
    "Birgland",
    "Birkenfeld",
    "Bischberg",
    "Bischbrunn",
    "Bischofsgrün",
    "Bischofsheim in der Rhön",
    "Bischofsmais",
    "Bischofswiesen",
    "Bissingen Markt",
    "Blaibach",
    "Blaichach",
    "Blankenbach",
    "Blindheim",
    "Böbing",
    "Bobingen",
    "Böbrach",
    "Bockhorn",
    "Bodenkirchen",
    "Bodenmais Markt",
    "Bodenwöhr",
    "Bodolz",
    "Bogen",
    "Böhen",
    "Böhmfeld",
    "Bolsterlang",
    "Bonstetten",
    "Boos",
    "Brand",
    "Brannenburg",
    "Breitbrunn (Unterfranken)",
    "Breitbrunn am Chiemsee",
    "Breitenberg",
    "Breitenbrunn (Oberpfalz) Markt",
    "Breitenbrunn (Schwaben)",
    "Breitengüßbach",
    "Breitenthal",
    "Brennberg",
    "Bruck (Oberbayern)",
    "Bruck in der Oberpfalz Markt",
    "Bruckberg (Niederbayern)",
    "Bruckberg (Mittelfranken)",
    "Bruckmühl Markt",
    "Brunn",
    "Brunnen",
    "Brunnthal",
    "Bubenreuth",
    "Bubesheim",
    "Buch (Schwaben) Markt",
    "Buch am Buchrain",
    "Buch am Erlbach",
    "Buch am Wald",
    "Buchbach Markt",
    "Buchbrunn",
    "Buchdorf",
    "Büchenbach",
    "Buchenberg Markt",
    "Buchhofen",
    "Büchlberg",
    "Buchloe",
    "Buckenhof",
    "Bundorf",
    "Burgau",
    "Burgberg im Allgäu",
    "Burgbernheim",
    "Burgebrach Markt",
    "Burggen",
    "Burghaslach Markt",
    "Burghausen",
    "Burgheim Markt",
    "Burgkirchen an der Alz",
    "Burgkunstadt",
    "Burglauer",
    "Burglengenfeld",
    "Burgoberbach",
    "Burgpreppach Markt",
    "Burgsalach",
    "Burgsinn Markt",
    "Bürgstadt Markt",
    "Burgthann",
    "Burgwindheim Markt",
    "Burk",
    "Burkardroth Markt",
    "Burtenbach Markt",
    "Buttenheim Markt",
    "Buttenwiesen",
    "Bütthard Markt",
    "Buxheim (Schwaben)",
    "Buxheim (Oberbayern)",
    "Cadolzburg Markt",
    "Castell",
    "Cham",
    "Chamerau",
    "Chieming",
    "Chiemsee",
    "Coburg",
    "Collenberg",
    "Colmberg Markt",
    "Creußen",
    "Dachau",
    "Dachsbach Markt",
    "Daiting",
    "Dammbach",
    "Dasing",
    "Deggendorf",
    "Deining",
    "Deiningen",
    "Deisenhausen",
    "Denkendorf",
    "Denklingen",
    "Dentlein am Forst Markt",
    "Dettelbach",
    "Deuerling",
    "Diebach",
    "Diedorf Markt",
    "Diespeck",
    "Dießen am Ammersee Markt",
    "Dietenhofen Markt",
    "Dietersburg",
    "Dietersheim",
    "Dieterskirchen",
    "Dietfurt an der Altmühl",
    "Dietmannsried Markt",
    "Dietramszell",
    "Dillingen an der Donau",
    "Dingolfing",
    "Dingolshausen",
    "Dinkelsbühl",
    "Dinkelscherben Markt",
    "Dirlewang Markt",
    "Dittelbrunn",
    "Dittenheim",
    "Döhlau",
    "Dollnstein Markt",
    "Dombühl Markt",
    "Donaustauf Markt",
    "Donauwörth",
    "Donnersdorf",
    "Dorfen",
    "Dörfles-Esbach",
    "Dorfprozelten",
    "Dormitz",
    "Drachselsried",
    "Duggendorf",
    "Durach",
    "Dürrlauingen",
    "Dürrwangen Markt",
    "Ebelsbach",
    "Ebensfeld Markt",
    "Eberfing",
    "Ebermannsdorf",
    "Ebermannstadt",
    "Ebern",
    "Ebersberg",
    "Ebersdorf bei Coburg",
    "Ebershausen",
    "Ebnath",
    "Ebrach Markt",
    "Eching (Lkr. Freising)",
    "Eching (Lkr. Landshut)",
    "Eching am Ammersee",
    "Eckental Markt",
    "Eckersdorf",
    "Edelsfeld",
    "Ederheim",
    "Edling",
    "Effeltrich",
    "Egenhofen",
    "Egg an der Günz",
    "Eggenfelden",
    "Eggenthal",
    "Egglham",
    "Egglkofen",
    "Eggolsheim Markt",
    "Eggstätt",
    "Eging am See Markt",
    "Eglfing",
    "Egling",
    "Egling an der Paar",
    "Egloffstein Markt",
    "Egmating",
    "Egweil",
    "Ehekirchen",
    "Ehingen (Lkr. Augsburg)",
    "Ehingen (Mittelfranken)",
    "Ehingen am Ries",
    "Eibelstadt",
    "Eichenau",
    "Eichenbühl",
    "Eichendorf Markt",
    "Eichstätt",
    "Eiselfing",
    "Eisenberg",
    "Eisenheim Markt",
    "Eisingen",
    "Eitensheim",
    "Eitting",
    "Elchingen",
    "Elfershausen Markt",
    "Ellgau",
    "Ellingen",
    "Ellzee",
    "Elsendorf",
    "Elsenfeld Markt",
    "Eltmann",
    "Emersacker",
    "Emmering (Lkr. Ebersberg)",
    "Emmering (Lkr. Fürstenfeldbruck)",
    "Emmerting",
    "Emskirchen Markt",
    "Emtmannsberg",
    "Engelsberg",
    "Engelthal",
    "Ensdorf",
    "Eppenschlag",
    "Eppishausen",
    "Erbendorf",
    "Erding",
    "Erdweg",
    "Eresing",
    "Ergersheim",
    "Ergolding Markt",
    "Ergoldsbach Markt",
    "Erharting",
    "Ering",
    "Erkheim Markt",
    "Erlabrunn",
    "Erlangen",
    "Erlbach",
    "Erlenbach am Main",
    "Erlenbach bei Marktheidenfeld",
    "Ermershausen",
    "Ernsgaden",
    "Eschau Markt",
    "Eschenbach in der Oberpfalz",
    "Eschenlohe",
    "Eschlkam Markt",
    "Eslarn Markt",
    "Esselbach",
    "Essenbach Markt",
    "Essing Markt",
    "Estenfeld",
    "Ettal",
    "Ettenstatt",
    "Ettringen",
    "Etzelwang",
    "Etzenricht",
    "Euerbach",
    "Euerdorf Markt",
    "Eurasburg (Oberbayern)",
    "Eurasburg (Schwaben)",
    "Eußenheim",
    "Fahrenzhausen",
    "Falkenberg (Niederbayern)",
    "Falkenberg (Oberpfalz) Markt",
    "Falkenfels",
    "Falkenstein Markt",
    "Farchant",
    "Faulbach",
    "Feichten an der Alz",
    "Feilitzsch",
    "Feldafing",
    "Feldkirchen (bei München)",
    "Feldkirchen (Niederbayern)",
    "Feldkirchen-Westerham",
    "Fellen",
    "Fellheim",
    "Fensterbach",
    "Feucht Markt",
    "Feuchtwangen",
    "Fichtelberg",
    "Finning",
    "Finningen",
    "Finsing",
    "Fischach Markt",
    "Fischbachau",
    "Fischen im Allgäu",
    "Flachslanden Markt",
    "Fladungen",
    "Flintsbach am Inn",
    "Floß Markt",
    "Flossenbürg",
    "Forchheim",
    "Forheim",
    "Forstern",
    "Forstinning",
    "Frammersbach Markt",
    "Frankenwinheim",
    "Frasdorf",
    "Frauenau",
    "Frauenneuharting",
    "Fraunberg",
    "Freihung Markt",
    "Freilassing",
    "Freising",
    "Fremdingen",
    "Frensdorf",
    "Freudenberg",
    "Freystadt",
    "Freyung",
    "Frickenhausen am Main Markt",
    "Fridolfing",
    "Friedberg",
    "Friedenfels",
    "Friesenried",
    "Frontenhausen Markt",
    "Fuchsmühl Markt",
    "Fuchsstadt",
    "Fuchstal",
    "Fünfstetten",
    "Fürsteneck",
    "Fürstenfeldbruck",
    "Fürstenstein",
    "Fürstenzell Markt",
    "Furth (Niederbayern)",
    "Furth im Wald",
    "Fürth",
    "Füssen",
    "Gablingen",
    "Gachenbach",
    "Gädheim",
    "Gaimersheim Markt",
    "Gaißach",
    "Gallmersgarten",
    "Gammelsdorf",
    "Gangkofen Markt",
    "Garching an der Alz",
    "Garching bei München",
    "Garmisch-Partenkirchen Markt",
    "Gars am Inn Markt",
    "Gattendorf",
    "Gaukönigshofen",
    "Gauting",
    "Gebenbach",
    "Gebsattel",
    "Gefrees",
    "Geiersthal",
    "Geiselbach",
    "Geiselhöring",
    "Geiselwind Markt",
    "Geisenfeld",
    "Geisenhausen Markt",
    "Gelchsheim Markt",
    "Geldersheim",
    "Geltendorf",
    "Gemünden am Main",
    "Genderkingen",
    "Georgenberg",
    "Georgensgmünd",
    "Gerach",
    "Geratskirchen",
    "Gerbrunn",
    "Geretsried",
    "Gerhardshofen",
    "Germaringen",
    "Germering",
    "Geroda Markt",
    "Geroldsgrün",
    "Geroldshausen",
    "Gerolfingen",
    "Gerolsbach",
    "Gerolzhofen",
    "Gersthofen",
    "Gerzen",
    "Gesees",
    "Geslau",
    "Gessertshausen",
    "Gestratz",
    "Giebelstadt Markt",
    "Gilching",
    "Glashütten",
    "Glattbach",
    "Gleiritsch",
    "Gleißenberg",
    "Glonn Markt",
    "Glött",
    "Gmund am Tegernsee",
    "Gnotzheim Markt",
    "Gochsheim",
    "Goldbach Markt",
    "Goldkronach",
    "Gollhofen",
    "Görisried",
    "Gössenheim",
    "Gößweinstein Markt",
    "Gotteszell",
    "Gottfrieding",
    "Graben",
    "Grabenstätt",
    "Gräfelfing",
    "Grafenau",
    "Gräfenberg",
    "Gräfendorf",
    "Grafengehaig Markt",
    "Grafenrheinfeld",
    "Grafenwiesen",
    "Grafenwöhr",
    "Grafing bei München",
    "Grafling",
    "Grafrath",
    "Grainau",
    "Grainet",
    "Grasbrunn",
    "Grassau Markt",
    "Grattersdorf",
    "Greding",
    "Greifenberg",
    "Greiling",
    "Gremsdorf",
    "Grettstadt",
    "Greußenheim",
    "Griesstätt",
    "Gröbenzell",
    "Großaitingen",
    "Großbardorf",
    "Großeibstadt",
    "Großenseebach",
    "Großhabersdorf",
    "Großheirath",
    "Großheubach Markt",
    "Großkarolinenfeld",
    "Großlangheim Markt",
    "Großmehring",
    "Großostheim Markt",
    "Großwallstadt",
    "Großweil",
    "Grub am Forst",
    "Grünenbach",
    "Grünwald",
    "Gstadt am Chiemsee",
    "Gundelfingen an der Donau",
    "Gundelsheim",
    "Gundremmingen",
    "Güntersleben",
    "Günzach",
    "Günzburg",
    "Gunzenhausen",
    "Guteneck",
    "Gutenstetten",
    "Guttenberg",
    "Haag (Oberfranken)",
    "Haag an der Amper",
    "Haag in Oberbayern Markt",
    "Haar",
    "Haarbach",
    "Habach",
    "Hafenlohr",
    "Hagelstadt",
    "Hagenbüchach",
    "Hahnbach Markt",
    "Haibach (Niederbayern)",
    "Haibach (Unterfranken)",
    "Haidmühle",
    "Haimhausen",
    "Haiming",
    "Hainsfarth",
    "Halblech",
    "Haldenwang (Lkr. Günzburg)",
    "Haldenwang (Lkr. Oberallgäu)",
    "Halfing",
    "Hallbergmoos",
    "Hallerndorf",
    "Hallstadt",
    "Halsbach",
    "Hammelburg",
    "Happurg",
    "Harburg (Schwaben)",
    "Harsdorf",
    "Hartenstein",
    "Haselbach",
    "Hasloch",
    "Haßfurt",
    "Hattenhofen",
    "Haundorf",
    "Haunsheim",
    "Hausen (Unterfranken)",
    "Hausen (Niederbayern)",
    "Hausen (Oberfranken)",
    "Hausen (Rhön)",
    "Hausen bei Würzburg",
    "Hausham",
    "Hauzenberg",
    "Hawangen",
    "Hebertsfelden",
    "Hebertshausen",
    "Heideck",
    "Heidenheim Markt",
    "Heigenbrücken",
    "Heiligenstadt in Oberfranken Markt",
    "Heilsbronn",
    "Heimbuchenthal",
    "Heimenkirch Markt",
    "Heimertingen",
    "Heinersreuth",
    "Heinrichsthal",
    "Heldenstein",
    "Helmbrechts",
    "Helmstadt Markt",
    "Hemau",
    "Hemhofen",
    "Hemmersheim",
    "Hendungen",
    "Henfenfeld",
    "Hengersberg Markt",
    "Hepberg",
    "Herbstadt",
    "Heretsried",
    "Hergatz",
    "Hergensweiler",
    "Heroldsbach",
    "Heroldsberg Markt",
    "Herrieden",
    "Herrngiersdorf",
    "Herrsching am Ammersee",
    "Hersbruck",
    "Herzogenaurach",
    "Heßdorf",
    "Hettenshausen",
    "Hettstadt",
    "Hetzles",
    "Heustreu",
    "Hilgertshausen-Tandern",
    "Hilpoltstein",
    "Hiltenfingen",
    "Hiltpoltstein Markt",
    "Himmelkron",
    "Himmelstadt",
    "Hinterschmiding",
    "Hirschaid Markt",
    "Hirschau",
    "Hirschbach",
    "Hitzhofen",
    "Höchberg Markt",
    "Höchheim",
    "Hochstadt am Main",
    "Höchstadt an der Aisch",
    "Höchstädt an der Donau",
    "Höchstädt im Fichtelgebirge",
    "Hof",
    "Hofheim in Unterfranken",
    "Hofkirchen Markt",
    "Hofstetten",
    "Hohenaltheim",
    "Hohenau",
    "Hohenberg an der Eger",
    "Hohenbrunn",
    "Hohenburg Markt",
    "Hohenfels Markt",
    "Hohenfurch",
    "Hohenkammer",
    "Höhenkirchen-Siegertsbrunn",
    "Hohenlinden",
    "Hohenpeißenberg",
    "Hohenpolding",
    "Hohenroth",
    "Hohenthann",
    "Hohenwart Markt",
    "Hohenwarth",
    "Hollenbach",
    "Hollfeld",
    "Hollstadt",
    "Holzgünz",
    "Holzheim (Donau-Ries)",
    "Holzheim (bei Neu-Ulm)",
    "Holzheim (bei Dillingen)",
    "Holzheim am Forst",
    "Holzkirchen (Oberbayern) Markt",
    "Holzkirchen (Unterfranken)",
    "Hopferau",
    "Horgau",
    "Hörgertshausen",
    "Hösbach Markt",
    "Höslwang",
    "Höttingen",
    "Huglfing",
    "Huisheim",
    "Hummeltal",
    "Hunderdorf",
    "Hunding",
    "Hurlach",
    "Hutthurm Markt",
    "Ichenhausen",
    "Icking",
    "Iffeldorf",
    "Igensdorf Markt",
    "Iggensbach",
    "Igling",
    "Ihrlerstein",
    "Illertissen",
    "Illesheim",
    "Illschwang",
    "Ilmmünster",
    "Immenreuth",
    "Immenstadt im Allgäu",
    "Inchenhofen Markt",
    "Ingenried",
    "Ingolstadt",
    "Innernzell",
    "Inning am Ammersee",
    "Inning am Holz",
    "Insingen",
    "Inzell",
    "Iphofen",
    "Ippesheim Markt",
    "Ipsheim Markt",
    "Irchenrieth",
    "Irlbach",
    "Irschenberg",
    "Irsee Markt",
    "Isen Markt",
    "Ismaning",
    "Issigau",
    "Itzgrund",
    "Jachenau",
    "Jandelsbrunn",
    "Jengen",
    "Jesenwang",
    "Jettenbach",
    "Jettingen-Scheppach Markt",
    "Jetzendorf",
    "Johannesberg",
    "Johanniskirchen",
    "Julbach",
    "Kahl am Main",
    "Kaisheim Markt",
    "Kalchreuth",
    "Kallmünz Markt",
    "Kaltental Markt",
    "Kammeltal",
    "Kammerstein",
    "Kammlach",
    "Karbach Markt",
    "Karlsfeld",
    "Karlshuld",
    "Karlskron",
    "Karlstadt",
    "Karlstein am Main",
    "Karsbach",
    "Kasendorf Markt",
    "Kastl (bei Kemnath)",
    "Kastl (Lauterachtal) Markt",
    "Kastl (Oberbayern)",
    "Kaufbeuren",
    "Kaufering Markt",
    "Kelheim",
    "Kellmünz an der Iller Markt",
    "Kemmern",
    "Kemnath",
    "Kempten (Allgäu)",
    "Kettershausen",
    "Kiefersfelden",
    "Kienberg",
    "Kinding Markt",
    "Kinsau",
    "Kipfenberg Markt",
    "Kirchanschöring",
    "Kirchberg (Oberbayern)",
    "Kirchberg im Wald",
    "Kirchdorf (Hallertau)",
    "Kirchdorf (bei Haag)",
    "Kirchdorf an der Amper",
    "Kirchdorf am Inn",
    "Kirchdorf im Wald",
    "Kirchehrenbach",
    "Kirchendemenreuth",
    "Kirchenlamitz",
    "Kirchenpingarten",
    "Kirchensittenbach",
    "Kirchenthumbach Markt",
    "Kirchham",
    "Kirchhaslach",
    "Kirchheim (Unterfranken)",
    "Kirchheim bei München",
    "Kirchheim in Schwaben Markt",
    "Kirchlauter",
    "Kirchroth",
    "Kirchseeon Markt",
    "Kirchweidach",
    "Kirchzell Markt",
    "Kissing",
    "Kist",
    "Kitzingen",
    "Kleinaitingen",
    "Kleinheubach Markt",
    "Kleinkahl",
    "Kleinlangheim Markt",
    "Kleinostheim",
    "Kleinrinderfeld",
    "Kleinsendelbach",
    "Kleinwallstadt Markt",
    "Klingenberg am Main",
    "Klosterlechfeld",
    "Knetzgau",
    "Kochel am See",
    "Köditz",
    "Ködnitz",
    "Köfering",
    "Kohlberg Markt",
    "Kolbermoor",
    "Kolitzheim",
    "Kollnburg",
    "Königsberg in Bayern",
    "Königsbrunn",
    "Königsdorf",
    "Königsfeld",
    "Königsmoos",
    "Königstein Markt",
    "Konnersreuth Markt",
    "Konradsreuth",
    "Konzell",
    "Kösching Markt",
    "Kößlarn Markt",
    "Kottgeisering",
    "Kötz",
    "Kraftisried",
    "Kraiburg am Inn Markt",
    "Krailling",
    "Kranzberg",
    "Kreuth",
    "Kreuzwertheim Markt",
    "Krombach",
    "Kronach",
    "Kronburg",
    "Kröning",
    "Krumbach (Schwaben)",
    "Krummennaab",
    "Krün",
    "Kühbach Markt",
    "Kühlenthal",
    "Kulmain",
    "Kulmbach",
    "Kumhausen",
    "Kümmersbruck",
    "Kunreuth",
    "Künzing",
    "Kupferberg",
    "Küps Markt",
    "Kürnach",
    "Kutzenhausen",
    "Laaber Markt",
    "Laberweinting",
    "Lachen",
    "Lalling",
    "Lam Markt",
    "Lamerdingen",
    "Landau an der Isar",
    "Landensberg",
    "Landsberg am Lech",
    "Landsberied",
    "Landshut",
    "Langdorf",
    "Langenaltheim",
    "Langenbach",
    "Langenfeld",
    "Langenmosen",
    "Langenneufnach",
    "Langenpreising",
    "Langensendelbach",
    "Langenzenn",
    "Langerringen",
    "Langfurth",
    "Langquaid Markt",
    "Langweid am Lech",
    "Lappersdorf Markt",
    "Lauben (Lkr. Oberallgäu)",
    "Lauben (Lkr. Unterallgäu)",
    "Laudenbach",
    "Lauf an der Pegnitz",
    "Laufach",
    "Laufen",
    "Laugna",
    "Lauingen (Donau)",
    "Lauter",
    "Lauterhofen Markt",
    "Lautertal",
    "Lautrach",
    "Lechbruck am See",
    "Legau Markt",
    "Lehrberg Markt",
    "Leiblfing",
    "Leidersbach",
    "Leinach",
    "Leinburg",
    "Leipheim",
    "Lengdorf",
    "Lengenwang",
    "Lenggries",
    "Lenting",
    "Leonberg",
    "Leuchtenberg Markt",
    "Leupoldsgrün",
    "Leutenbach",
    "Leutershausen",
    "Lichtenau Markt",
    "Lichtenberg",
    "Lichtenfels",
    "Lindau (Bodensee)",
    "Lindberg",
    "Lindenberg im Allgäu",
    "Lisberg",
    "Litzendorf",
    "Lohberg",
    "Lohkirchen",
    "Lohr am Main",
    "Loiching",
    "Loitzendorf",
    "Lonnerstadt Markt",
    "Ludwigschorgast Markt",
    "Ludwigsstadt",
    "Luhe-Wildenau Markt",
    "Lülsfeld",
    "Lupburg Markt",
    "Lutzingen",
    "Mähring Markt",
    "Maierhöfen",
    "Maihingen",
    "Mainaschaff",
    "Mainbernheim",
    "Mainburg",
    "Mainleus Markt",
    "Mainstockheim",
    "Maisach",
    "Maitenbeth",
    "Malching",
    "Malgersdorf",
    "Mallersdorf-Pfaffenberg Markt",
    "Mammendorf",
    "Mamming",
    "Manching Markt",
    "Mantel Markt",
    "Margetshöchheim",
    "Mariaposching",
    "Marklkofen",
    "Marktbergel Markt",
    "Markt Berolzheim Markt",
    "Marktbreit",
    "Markt Bibart Markt",
    "Markt Einersheim Markt",
    "Markt Erlbach Markt",
    "Marktgraitz Markt",
    "Marktheidenfeld",
    "Markt Indersdorf Markt",
    "Marktl Markt",
    "Marktleugast Markt",
    "Marktleuthen",
    "Markt Nordheim Markt",
    "Marktoberdorf",
    "Marktoffingen",
    "Marktredwitz",
    "Markt Rettenbach Markt",
    "Marktrodach Markt",
    "Marktschellenberg Markt",
    "Marktschorgast Markt",
    "Markt Schwaben Markt",
    "Marktsteft",
    "Markt Taschendorf Markt",
    "Markt Wald Markt",
    "Marktzeuln Markt",
    "Marloffstein",
    "Maroldsweisach Markt",
    "Marquartstein",
    "Martinsheim",
    "Marxheim",
    "Marzling",
    "Maßbach Markt",
    "Massing Markt",
    "Mauern",
    "Mauerstetten",
    "Mauth",
    "Maxhütte-Haidhof",
    "Medlingen",
    "Meeder",
    "Megesheim",
    "Mehlmeisel",
    "Mehring",
    "Meinheim",
    "Meitingen Markt",
    "Mellrichstadt",
    "Memmelsdorf",
    "Memmingen",
    "Memmingerberg",
    "Mengkofen",
    "Merching",
    "Mering Markt",
    "Merkendorf",
    "Mertingen",
    "Mespelbrunn",
    "Metten Markt",
    "Mettenheim",
    "Michelau in Oberfranken",
    "Michelau im Steigerwald",
    "Michelsneukirchen",
    "Mickhausen",
    "Miesbach",
    "Miltach",
    "Miltenberg",
    "Mindelheim",
    "Mindelstetten",
    "Mintraching",
    "Missen-Wilhams",
    "Mistelbach",
    "Mistelgau",
    "Mitteleschenbach",
    "Mittelneufnach",
    "Mittelsinn",
    "Mittelstetten",
    "Mittenwald Markt",
    "Mitterfels Markt",
    "Mitterskirchen",
    "Mitterteich",
    "Mitwitz Markt",
    "Mödingen",
    "Möhrendorf",
    "Mömbris Markt",
    "Mömlingen",
    "Mönchberg Markt",
    "Mönchsdeggingen",
    "Mönchsroth",
    "Monheim",
    "Moorenweis",
    "Moos",
    "Moosach",
    "Moosbach Markt",
    "Moosburg an der Isar",
    "Moosinning",
    "Moosthenning",
    "Mörnsheim Markt",
    "Motten",
    "Möttingen",
    "Mötzing",
    "Mühldorf am Inn",
    "Mühlhausen (Franken) Markt",
    "Mühlhausen (Oberpfalz)",
    "Muhr am See",
    "Münchberg",
    "München Landeshauptstadt",
    "Münchsmünster",
    "Münchsteinach",
    "Münnerstadt",
    "Munningen",
    "Münsing",
    "Münster",
    "Münsterhausen Markt",
    "Murnau am Staffelsee Markt",
    "Nabburg",
    "Nagel",
    "Naila",
    "Nandlstadt Markt",
    "Nassenfels Markt",
    "Nennslingen Markt",
    "Nersingen",
    "Nesselwang Markt",
    "Neubeuern Markt",
    "Neubiberg",
    "Neubrunn Markt",
    "Neuburg an der Donau",
    "Neuburg an der Kammel Markt",
    "Neuburg am Inn",
    "Neuching",
    "Neudrossenfeld",
    "Neuendettelsau",
    "Neuendorf",
    "Neuenmarkt",
    "Neufahrn bei Freising",
    "Neufahrn in Niederbayern",
    "Neufraunhofen",
    "Neuhaus an der Pegnitz Markt",
    "Neuhaus am Inn",
    "Neuhof an der Zenn Markt",
    "Neuhütten",
    "Neukirchen (Niederbayern)",
    "Neukirchen beim Heiligen Blut Markt",
    "Neukirchen bei Sulzbach-Rosenberg",
    "Neukirchen-Balbini Markt",
    "Neukirchen vorm Wald",
    "Neumarkt in der Oberpfalz",
    "Neumarkt-Sankt Veit",
    "Neunburg vorm Wald",
    "Neunkirchen (Unterfranken)",
    "Neunkirchen am Brand Markt",
    "Neunkirchen am Sand",
    "Neuötting",
    "Neureichenau",
    "Neuried",
    "Neusäß",
    "Neuschönau",
    "Neusitz",
    "Neusorg",
    "Neustadt am Kulm",
    "Neustadt am Main",
    "Neustadt an der Aisch",
    "Neustadt an der Donau",
    "Neustadt an der Waldnaab",
    "Neustadt bei Coburg",
    "Neutraubling",
    "Neu-Ulm",
    "Niederaichbach",
    "Niederalteich",
    "Niederbergkirchen",
    "Niederfüllbach",
    "Niederlauer",
    "Niedermurach",
    "Niedernberg",
    "Niederrieden",
    "Niederschönenfeld",
    "Niedertaufkirchen",
    "Niederviehbach",
    "Niederwerrn",
    "Niederwinkling",
    "Nittenau",
    "Nittendorf Markt",
    "Nonnenhorn",
    "Nordendorf",
    "Nordhalben Markt",
    "Nordheim am Main",
    "Nordheim vor der Rhön",
    "Nördlingen",
    "Nüdlingen",
    "Nürnberg",
    "Nußdorf (Chiemgau)",
    "Nußdorf am Inn",
    "Oberammergau",
    "Oberasbach",
    "Oberau",
    "Oberaudorf",
    "Oberaurach",
    "Oberbergkirchen",
    "Oberdachstetten",
    "Oberding",
    "Oberdolling",
    "Oberelsbach Markt",
    "Obergriesbach",
    "Obergünzburg Markt",
    "Oberhaching",
    "Oberhaid",
    "Oberhausen (b. Neuburg)",
    "Oberhausen (b. Peißenberg)",
    "Oberickelsheim",
    "Oberkotzau Markt",
    "Oberleichtersbach",
    "Obermaiselstein",
    "Obermeitingen",
    "Obermichelbach",
    "Obernbreit Markt",
    "Obernburg am Main",
    "Oberndorf am Lech",
    "Oberneukirchen",
    "Obernzell Markt",
    "Obernzenn Markt",
    "Oberostendorf",
    "Oberottmarshausen",
    "Oberpframmern",
    "Oberpleichfeld",
    "Oberpöring",
    "Oberreichenbach",
    "Oberreute",
    "Oberrieden",
    "Oberroth",
    "Oberscheinfeld Markt",
    "Oberschleißheim",
    "Oberschneiding",
    "Oberschönegg",
    "Oberschwarzach Markt",
    "Oberschweinbach",
    "Obersinn Markt",
    "Obersöchering",
    "Oberstaufen Markt",
    "Oberstdorf Markt",
    "Oberstreu",
    "Obersüßbach",
    "Obertaufkirchen",
    "Oberthulba Markt",
    "Obertraubling",
    "Obertrubach",
    "Oberviechtach",
    "Obing",
    "Ochsenfurt",
    "Odelzhausen",
    "Oerlenbach",
    "Oettingen in Bayern",
    "Offenberg",
    "Offenhausen",
    "Offingen Markt",
    "Ofterschwang",
    "Ohlstadt",
    "Ohrenbach",
    "Olching",
    "Opfenbach",
    "Ornbau",
    "Ortenburg Markt",
    "Osterberg",
    "Osterhofen",
    "Osterzell",
    "Ostheim vor der Rhön",
    "Ottenhofen",
    "Ottensoos",
    "Otterfing",
    "Otting",
    "Ottobeuren Markt",
    "Ottobrunn",
    "Otzing",
    "Oy-Mittelberg",
    "Pähl",
    "Painten Markt",
    "Palling",
    "Pappenheim",
    "Parkstein Markt",
    "Parkstetten",
    "Parsberg",
    "Partenstein",
    "Passau",
    "Pastetten",
    "Patersdorf",
    "Paunzhausen",
    "Pechbrunn",
    "Pegnitz",
    "Peißenberg Markt",
    "Peiting Markt",
    "Pemfling",
    "Pentling",
    "Penzberg",
    "Penzing",
    "Perach",
    "Perasdorf",
    "Perkam",
    "Perlesreut Markt",
    "Petersaurach",
    "Petersdorf",
    "Petershausen",
    "Pettendorf",
    "Petting",
    "Pettstadt",
    "Pfaffenhausen Markt",
    "Pfaffenhofen an der Glonn",
    "Pfaffenhofen an der Ilm",
    "Pfaffenhofen an der Roth Markt",
    "Pfaffing",
    "Pfakofen",
    "Pfarrkirchen",
    "Pfarrweisach",
    "Pfatter",
    "Pfeffenhausen Markt",
    "Pfofeld",
    "Pförring Markt",
    "Pforzen",
    "Pfreimd",
    "Pfronten",
    "Philippsreut",
    "Piding",
    "Pielenhofen",
    "Pilsach",
    "Pilsting Markt",
    "Pinzberg",
    "Pirk",
    "Pittenhart",
    "Planegg",
    "Plankenfels",
    "Plattling",
    "Plech Markt",
    "Pleinfeld Markt",
    "Pleiskirchen",
    "Pleß",
    "Pleystein",
    "Pliening",
    "Plößberg Markt",
    "Pocking",
    "Pöcking",
    "Poing",
    "Pollenfeld",
    "Polling (b. Mühldorf)",
    "Polling (b. Weilheim)",
    "Polsingen",
    "Pommelsbrunn",
    "Pommersfelden",
    "Poppenhausen",
    "Poppenricht",
    "Pörnbach",
    "Pösing",
    "Postau",
    "Postbauer-Heng Markt",
    "Postmünster",
    "Pottenstein",
    "Pöttmes Markt",
    "Poxdorf",
    "Prackenbach",
    "Prebitz",
    "Prem",
    "Pressath",
    "Presseck Markt",
    "Pressig Markt",
    "Pretzfeld Markt",
    "Prichsenstadt",
    "Prien am Chiemsee Markt",
    "Priesendorf",
    "Prittriching",
    "Prosselsheim",
    "Prutting",
    "Püchersreuth",
    "Puchheim",
    "Pullach im Isartal",
    "Pullenreuth",
    "Pürgen",
    "Puschendorf",
    "Putzbrunn",
    "Pyrbaum Markt",
    "Rain (am Lech)",
    "Rain (Niederbayern)",
    "Raisting",
    "Raitenbuch",
    "Ramerberg",
    "Rammingen",
    "Ramsau bei Berchtesgaden",
    "Ramsthal",
    "Randersacker Markt",
    "Rannungen",
    "Rattelsdorf Markt",
    "Rattenberg",
    "Rattenkirchen",
    "Rattiszell",
    "Raubling",
    "Rauhenebrach",
    "Rechtenbach",
    "Rechtmehring",
    "Reckendorf",
    "Rednitzhembach",
    "Redwitz an der Rodach",
    "Regen",
    "Regensburg",
    "Regenstauf Markt",
    "Regnitzlosau",
    "Rehau",
    "Rehling",
    "Reichenbach (Landkreis Cham)",
    "Reichenbach (Landkreis Kronach)",
    "Reichenberg Markt",
    "Reichenschwand",
    "Reichersbeuern",
    "Reichertshausen",
    "Reichertsheim",
    "Reichertshofen Markt",
    "Reichling",
    "Reimlingen",
    "Reisbach Markt",
    "Reischach",
    "Reit im Winkl",
    "Remlingen Markt",
    "Rennertshofen Markt",
    "Rentweinsdorf Markt",
    "Rettenbach (Landkr. Günzburg)",
    "Rettenbach (Oberpfalz)",
    "Rettenbach am Auerberg",
    "Rettenberg",
    "Retzstadt",
    "Reut",
    "Reuth bei Erbendorf",
    "Ried",
    "Riedbach",
    "Rieden (Oberpfalz) Markt",
    "Rieden (b. Kaufbeuren)",
    "Rieden am Forggensee",
    "Riedenberg",
    "Riedenburg",
    "Riedenheim",
    "Riedering",
    "Riegsee",
    "Riekofen",
    "Rieneck",
    "Rimbach (Landkreis Rottal-Inn)",
    "Rimbach (Oberpfalz)",
    "Rimpar Markt",
    "Rimsting",
    "Rinchnach",
    "Ringelai",
    "Röckingen",
    "Rödelmaier",
    "Rödelsee",
    "Roden",
    "Rödental",
    "Roding",
    "Röfingen",
    "Roggenburg",
    "Rögling",
    "Rohr (Mittelfranken)",
    "Rohr in Niederbayern Markt",
    "Rohrbach",
    "Rohrdorf",
    "Rohrenfels",
    "Röhrmoos",
    "Röhrnbach Markt",
    "Röllbach",
    "Ronsberg Markt",
    "Rosenheim",
    "Röslau",
    "Roßbach",
    "Roßhaupten",
    "Roßtal Markt",
    "Roth",
    "Röthenbach (Allgäu)",
    "Röthenbach an der Pegnitz",
    "Rothenbuch",
    "Rothenburg ob der Tauber",
    "Rothenfels",
    "Röthlein",
    "Rott (Landkr. Landsberg)",
    "Rott am Inn",
    "Rottach-Egern",
    "Röttenbach (b. Erlangen)",
    "Röttenbach (Landkr. Roth)",
    "Rottenbuch",
    "Rottenburg an der Laaber",
    "Rottendorf",
    "Rotthalmünster Markt",
    "Röttingen",
    "Rötz",
    "Rückersdorf",
    "Rückholz",
    "Rudelzhausen",
    "Rüdenau",
    "Rüdenhausen Markt",
    "Ruderatshofen",
    "Ruderting",
    "Rugendorf",
    "Rügland",
    "Ruhmannsfelden Markt",
    "Ruhpolding",
    "Ruhstorf an der Rott Markt",
    "Runding",
    "Saal an der Donau",
    "Saal an der Saale Markt",
    "Saaldorf-Surheim",
    "Sachsen bei Ansbach",
    "Sachsenkam",
    "Sailauf",
    "Salching",
    "Saldenburg",
    "Salgen",
    "Salz",
    "Salzweg",
    "Samerberg",
    "Sand am Main",
    "Sandberg",
    "Sankt Englmar",
    "Sankt Oswald-Riedlhütte",
    "Sankt Wolfgang",
    "Sauerlach",
    "Saulgrub",
    "Schäftlarn",
    "Schalkham",
    "Schauenstein",
    "Schaufling",
    "Schechen",
    "Scheidegg Markt",
    "Scheinfeld",
    "Schernfeld",
    "Scherstetten",
    "Scheßlitz",
    "Scheuring",
    "Scheyern",
    "Schierling Markt",
    "Schillingsfürst",
    "Schiltberg",
    "Schirmitz",
    "Schirnding Markt",
    "Schlammersdorf",
    "Schleching",
    "Schlehdorf",
    "Schliersee Markt",
    "Schlüsselfeld",
    "Schmidgaden",
    "Schmidmühlen Markt",
    "Schmiechen",
    "Schnabelwaid Markt",
    "Schnaitsee",
    "Schnaittach Markt",
    "Schnaittenbach",
    "Schneckenlohe",
    "Schneeberg Markt",
    "Schneizlreuth",
    "Schnelldorf",
    "Schöfweg",
    "Schollbrunn",
    "Schöllkrippen Markt",
    "Schöllnach Markt",
    "Schönau (Niederbayern)",
    "Schönau an der Brend",
    "Schönau am Königssee",
    "Schönberg (Niederbayern) Markt",
    "Schönberg (Oberbayern)",
    "Schönbrunn im Steigerwald",
    "Schondorf am Ammersee",
    "Schondra Markt",
    "Schongau",
    "Schöngeising",
    "Schönsee",
    "Schonstett",
    "Schönthal",
    "Schonungen",
    "Schönwald",
    "Schopfloch Markt",
    "Schorndorf",
    "Schrobenhausen",
    "Schwabach",
    "Schwabbruck",
    "Schwabhausen",
    "Schwabmünchen",
    "Schwabsoien",
    "Schwaig bei Nürnberg",
    "Schwaigen",
    "Schwandorf",
    "Schwanfeld",
    "Schwangau",
    "Schwanstetten Markt",
    "Schwarzach (Niederbayern) Markt",
    "Schwarzach am Main Markt",
    "Schwarzach bei Nabburg",
    "Schwarzenbach (Oberpfalz)",
    "Schwarzenbach am Wald",
    "Schwarzenbach an der Saale",
    "Schwarzenbruck",
    "Schwarzenfeld Markt",
    "Schwarzhofen Markt",
    "Schwebheim",
    "Schweinfurt",
    "Schweitenkirchen",
    "Schwenningen",
    "Schwifting",
    "Schwindegg",
    "Seefeld",
    "Seeg",
    "Seehausen am Staffelsee",
    "Seeon-Seebruck",
    "Seeshaupt",
    "Segnitz",
    "Seinsheim Markt",
    "Selb",
    "Selbitz",
    "Senden",
    "Sengenthal",
    "Sennfeld",
    "Seßlach",
    "Seubersdorf in der Oberpfalz",
    "Seukendorf",
    "Seybothenreuth",
    "Siegenburg Markt",
    "Siegsdorf",
    "Sielenbach",
    "Sigmarszell",
    "Simbach (b. Landau) Markt",
    "Simbach am Inn",
    "Simmelsdorf",
    "Simmershofen",
    "Sindelsdorf",
    "Sinzing",
    "Söchtenau",
    "Solnhofen",
    "Sommerach",
    "Sommerhausen Markt",
    "Sommerkahl",
    "Sonderhofen",
    "Sondheim vor der Rhön",
    "Sonnefeld",
    "Sonnen",
    "Sontheim",
    "Sonthofen",
    "Soyen",
    "Spalt",
    "Spardorf",
    "Sparneck Markt",
    "Spatzenhausen",
    "Speichersdorf",
    "Speinshart",
    "Spiegelau",
    "Stadelhofen",
    "Stadlern",
    "Stadtbergen",
    "Stadtlauringen Markt",
    "Stadtprozelten",
    "Stadtsteinach",
    "Stallwang",
    "Stammbach Markt",
    "Stammham (am Inn)",
    "Stammham (b. Ingolstadt)",
    "Stamsried Markt",
    "Starnberg",
    "Staudach-Egerndach",
    "Stegaurach",
    "Stein",
    "Steinach",
    "Steinbach am Wald",
    "Steinberg am See",
    "Steindorf",
    "Steinfeld",
    "Steingaden",
    "Steinhöring",
    "Steinkirchen",
    "Steinsfeld",
    "Steinwiesen Markt",
    "Stephanskirchen",
    "Stephansposching",
    "Stetten",
    "Stettfeld",
    "Stiefenhofen",
    "Stockheim (Oberfranken)",
    "Stockheim (Unterfranken)",
    "Stockstadt am Main Markt",
    "Störnstein",
    "Stötten am Auerberg",
    "Stöttwang",
    "Strahlungen",
    "Straßkirchen",
    "Straßlach-Dingharting",
    "Straubing",
    "Strullendorf",
    "Stubenberg",
    "Stulln",
    "Sugenheim Markt",
    "Sulzbach am Main Markt",
    "Sulzbach-Rosenberg",
    "Sulzberg Markt",
    "Sulzdorf an der Lederhecke",
    "Sulzemoos",
    "Sulzfeld (im Grabfeld)",
    "Sulzfeld am Main",
    "Sulzheim",
    "Sulzthal Markt",
    "Sünching",
    "Surberg",
    "Syrgenstein",
    "Tacherting",
    "Taching am See",
    "Tagmersheim",
    "Tann Markt",
    "Tännesberg Markt",
    "Tapfheim",
    "Tauberrettersheim",
    "Taufkirchen (Landkr. Mühldorf)",
    "Taufkirchen (b. München)",
    "Taufkirchen (Vils)",
    "Tegernheim",
    "Tegernsee",
    "Teisendorf Markt",
    "Teising",
    "Teisnach Markt",
    "Tettau Markt",
    "Tettenweis",
    "Teublitz",
    "Teugn",
    "Teunz",
    "Teuschnitz",
    "Thaining",
    "Thalmassing",
    "Thalmässing Markt",
    "Thannhausen",
    "Thanstein",
    "Theilenhofen",
    "Theilheim",
    "Theisseil",
    "Theres",
    "Thierhaupten Markt",
    "Thiersheim Markt",
    "Thierstein Markt",
    "Thundorf in Unterfranken",
    "Thüngen Markt",
    "Thüngersheim",
    "Thurmansbang",
    "Thurnau Markt",
    "Thyrnau",
    "Tiefenbach (b. Landshut)",
    "Tiefenbach (b. Passau)",
    "Tiefenbach (Oberpfalz)",
    "Tirschenreuth",
    "Titting Markt",
    "Tittling Markt",
    "Tittmoning",
    "Todtenweis",
    "Töging am Inn",
    "Töpen",
    "Trabitz",
    "Train",
    "Traitsching",
    "Trappstadt Markt",
    "Traunreut",
    "Traunstein",
    "Trausnitz",
    "Trautskirchen",
    "Trebgast",
    "Treffelstein",
    "Treuchtlingen",
    "Triefenstein Markt",
    "Triftern Markt",
    "Trogen",
    "Tröstau",
    "Trostberg",
    "Trunkelsberg",
    "Tschirn",
    "Tuchenbach",
    "Tuntenhausen",
    "Türkenfeld",
    "Türkheim Markt",
    "Tussenhausen Markt",
    "Tüßling Markt",
    "Tutzing",
    "Tyrlaching",
    "Übersee",
    "Üchtelhausen",
    "Uffenheim",
    "Uffing am Staffelsee",
    "Uehlfeld Markt",
    "Uettingen",
    "Ungerhausen",
    "Unsleben",
    "Unterammergau",
    "Unterdießen",
    "Unterdietfurt",
    "Unteregg",
    "Unterföhring",
    "Untergriesbach Markt",
    "Unterhaching",
    "Unterleinleiter",
    "Untermeitingen",
    "Untermerzbach",
    "Unterneukirchen",
    "Unterpleichfeld",
    "Unterreit",
    "Unterroth",
    "Unterschleißheim",
    "Unterschwaningen",
    "Untersiemau",
    "Untersteinach",
    "Unterthingau Markt",
    "Unterwössen",
    "Untrasried",
    "Ursberg",
    "Ursensollen",
    "Urspringen",
    "Ustersbach",
    "Uttenreuth",
    "Utting am Ammersee",
    "Vachendorf",
    "Valley",
    "Vaterstetten",
    "Veitsbronn",
    "Veitshöchheim",
    "Velburg",
    "Velden (Mittelfranken)",
    "Velden (Niederbayern) Markt",
    "Vestenbergsgreuth Markt",
    "Viechtach",
    "Viereth-Trunstadt",
    "Vierkirchen",
    "Vilgertshofen",
    "Villenbach",
    "Vilsbiburg",
    "Vilseck",
    "Vilsheim",
    "Vilshofen an der Donau",
    "Vogtareuth",
    "Vohburg an der Donau",
    "Vohenstrauß",
    "Vöhringen",
    "Volkach",
    "Volkenschwand",
    "Vorbach",
    "Vorra",
    "Waakirchen",
    "Waal Markt",
    "Wachenroth Markt",
    "Wackersberg",
    "Wackersdorf",
    "Waffenbrunn",
    "Waging am See Markt",
    "Waidhaus Markt",
    "Waidhofen",
    "Waigolshausen",
    "Waischenfeld",
    "Wald (Schwaben)",
    "Wald (Oberpfalz)",
    "Waldaschaff",
    "Waldbrunn",
    "Waldbüttelbrunn",
    "Walderbach",
    "Waldershof",
    "Waldkirchen",
    "Waldkraiburg",
    "Waldmünchen",
    "Waldsassen",
    "Waldstetten Markt",
    "Waldthurn Markt",
    "Walkertshofen",
    "Wallenfels",
    "Wallerfing",
    "Wallersdorf Markt",
    "Wallerstein Markt",
    "Wallgau",
    "Walpertskirchen",
    "Walsdorf",
    "Waltenhausen",
    "Waltenhofen",
    "Walting",
    "Wang",
    "Warmensteinach",
    "Warngau",
    "Wartenberg Markt",
    "Wartmannsroth",
    "Wasserburg (Bodensee)",
    "Wasserburg am Inn",
    "Wasserlosen",
    "Wassertrüdingen",
    "Wattendorf",
    "Wechingen",
    "Wegscheid Markt",
    "Wehringen",
    "Weibersbrunn",
    "Weichering",
    "Weichs",
    "Weiden in der Oberpfalz",
    "Weidenbach Markt",
    "Weidenberg Markt",
    "Weidhausen bei Coburg",
    "Weiding (Lkr. Cham)",
    "Weiding (Lkr. Schwandorf)",
    "Weigendorf",
    "Weigenheim",
    "Weihenzell",
    "Weiherhammer",
    "Weihmichl",
    "Weil",
    "Weilbach Markt",
    "Weiler-Simmerberg Markt",
    "Weilersbach",
    "Weilheim in Oberbayern",
    "Weiltingen Markt",
    "Weisendorf Markt",
    "Weismain",
    "Weißdorf",
    "Weißenbrunn",
    "Weißenburg in Bayern",
    "Weißenhorn",
    "Weißenohe",
    "Weißensberg",
    "Weißenstadt",
    "Weitnau Markt",
    "Weitramsdorf",
    "Welden Markt",
    "Wellheim Markt",
    "Wemding",
    "Wendelstein Markt",
    "Weng",
    "Wenzenbach",
    "Wernberg-Köblitz Markt",
    "Werneck Markt",
    "Wertach Markt",
    "Wertingen",
    "Weßling",
    "Wessobrunn",
    "Westendorf (Lkr. Ostallgäu)",
    "Westendorf (Lkr. Augsburg)",
    "Westerheim",
    "Westerngrund",
    "Westheim",
    "Wettringen",
    "Wettstetten",
    "Weyarn",
    "Wiedergeltingen",
    "Wielenbach",
    "Wiesau Markt",
    "Wiesen",
    "Wiesenbach",
    "Wiesenbronn",
    "Wiesenfelden",
    "Wiesent",
    "Wiesenthau",
    "Wiesentheid Markt",
    "Wiesenttal Markt",
    "Wieseth",
    "Wiesthal",
    "Wiggensbach Markt",
    "Wilburgstetten",
    "Wildenberg",
    "Wildflecken Markt",
    "Wildpoldsried",
    "Wildsteig",
    "Wilhelmsdorf",
    "Wilhelmsthal",
    "Wilhermsdorf Markt",
    "Willanzheim Markt",
    "Willmars",
    "Willmering",
    "Windach",
    "Windberg",
    "Windelsbach",
    "Windischeschenbach",
    "Windorf Markt",
    "Windsbach",
    "Winhöring",
    "Winkelhaid",
    "Winklarn Markt",
    "Winterbach",
    "Winterhausen Markt",
    "Winterrieden",
    "Winzer Markt",
    "Wipfeld",
    "Wirsberg Markt",
    "Wittelshofen",
    "Wittibreut",
    "Wittislingen Markt",
    "Witzmannsberg",
    "Wolfersdorf",
    "Wolferstadt",
    "Wolfertschwenden",
    "Wolframs-Eschenbach",
    "Wolfratshausen",
    "Wolfsegg",
    "Wollbach",
    "Wolnzach Markt",
    "Wonfurt",
    "Wonneberg",
    "Wonsees Markt",
    "Woringen",
    "Wörnitz",
    "Wörth (Lkr. Erding)",
    "Wörth am Main",
    "Wörth an der Donau",
    "Wörth an der Isar",
    "Wörthsee",
    "Wülfershausen an der Saale",
    "Wunsiedel",
    "Wurmannsquick Markt",
    "Wurmsham",
    "Würzburg",
    "Zachenberg",
    "Zandt",
    "Zangberg",
    "Zapfendorf Markt",
    "Zeil am Main",
    "Zeilarn",
    "Zeitlarn",
    "Zeitlofs Markt",
    "Zell (Oberpfalz)",
    "Zell im Fichtelgebirge Markt",
    "Zell am Main Markt",
    "Zellingen Markt",
    "Zenting",
    "Ziemetshausen Markt",
    "Ziertheim",
    "Zirndorf",
    "Zolling",
    "Zorneding",
    "Zöschingen",
    "Zusamaltheim",
    "Zusmarshausen Markt",
    "Zwiesel",
    "Altdorf b.Nürnberg",
    "Altenmarkt a.d.Alz",
    "Altenstadt a.d.Waldnaab",
    "Aschau a.Inn",
    "Aschau i.Chiemgau",
    "Au i.d.Hallertau",
    "Auerbach i.d.OPf.",
    "Aura a.d.Saale",
    "Aura i.Sinngrund",
    "Bach a.d.Donau",
    "Bächingen a.d.Brenz",
    "Bad Berneck i.Fichtelgebirge",
    "Bad Griesbach i.Rottal",
    "Bad Königshofen i.Grabfeld",
    "Bad Neustadt a.d.Saale",
    "Bayerbach b.Ergoldsbach",
    "Berg b.Neumarkt i.d.OPf.",
    "Bernau a.Chiemsee",
    "Bischofsheim a.d.Rhön",
    "Breitbrunn a.Chiemsee",
    "Bruck i.d.OPf.",
    "Buch a.Buchrain",
    "Buch a.Erlbach",
    "Buch a.Wald",
    "Burgberg i.Allgäu",
    "Burgkirchen a.d.Alz",
    "Dentlein a.Forst",
    "Dießen a.Ammersee",
    "Dietfurt a.d.Altmühl",
    "Dillingen a.d.Donau",
    "Ebersdorf b.Coburg",
    "Eching a.Ammersee",
    "Egg a.d.Günz",
    "Eging a.See",
    "Egling a.d.Paar",
    "Ehingen a.Ries",
    "Erlenbach a.Main",
    "Erlenbach b.Marktheidenfeld",
    "Eschenbach i.d.OPf.",
    "Feichten a.d.Alz",
    "Fischen i.Allgäu",
    "Flintsbach a.Inn",
    "Frickenhausen a.Main",
    "Garching a.d.Alz",
    "Garching b.München",
    "Gars a.Inn",
    "Gemünden a.Main",
    "Gmund a.Tegernsee",
    "Grafing b.München",
    "Grub a.Forst",
    "Gstadt a.Chiemsee",
    "Gundelfingen a.d.Donau",
    "Haag a.d.Amper",
    "Haag i.OB",
    "Hausen b.Würzburg",
    "Heiligenstadt i.OFr.",
    "Herrsching a.Ammersee",
    "Höchstadt a.d.Aisch",
    "Höchstädt a.d.Donau",
    "Hochstadt a.Main",
    "Höchstädt i.Fichtelgebirge",
    "Hofheim i.UFr.",
    "Hohenberg a.d.Eger",
    "Holzheim a.Forst",
    "Immenstadt i.Allgäu",
    "Inning a.Ammersee",
    "Inning a.Holz",
    "Kahl a.Main",
    "Karlstein a.Main",
    "Kellmünz a.d.Iller",
    "Kirchberg i.Wald",
    "Kirchdorf a.d.Amper",
    "Kirchdorf a.Inn",
    "Kirchdorf i.Wald",
    "Kirchheim b.München",
    "Kirchheim i.Schw.",
    "Klingenberg a.Main",
    "Kochel a.See",
    "Königsberg i.Bay.",
    "Kraiburg a.Inn",
    "Landau a.d.Isar",
    "Langweid a.Lech",
    "Lauf a.d.Pegnitz",
    "Lechbruck a.See",
    "Lindenberg i.Allgäu",
    "Lohr a.Main",
    "Michelau i.OFr.",
    "Michelau i.Steigerwald",
    "Moosburg a.d.Isar",
    "Mühldorf a.Inn",
    "Muhr a.See",
    "Murnau a.Staffelsee",
    "Neuburg a.d.Donau",
    "Neuburg a.d.Kammel",
    "Neuburg a.Inn",
    "Neufahrn b.Freising",
    "Neufahrn i.NB",
    "Neuhaus a.d.Pegnitz",
    "Neuhaus a.Inn",
    "Neuhof a.d.Zenn",
    "Neukirchen b.Hl.Blut",
    "Neukirchen b.Sulzbach-Rosenberg",
    "Neumarkt i.d.OPf.",
    "Neunkirchen a.Brand",
    "Neunkirchen a.Sand",
    "Neustadt a.d.Aisch",
    "Neustadt a.d.Donau",
    "Neustadt a.d.Waldnaab",
    "Neustadt a.Main",
    "Neustadt b.Coburg",
    "Nordheim a.Main",
    "Nordheim v.d.Rhön",
    "Nußdorf a.Inn",
    "Obernburg a.Main",
    "Oberndorf a.Lech",
    "Oettingen i.Bay.",
    "Ostheim v.d.Rhön",
    "Pfaffenhofen a.d.Glonn",
    "Pfaffenhofen a.d.Ilm",
    "Pfaffenhofen a.d.Roth",
    "Prien a.Chiemsee",
    "Pullach i.Isartal",
    "Ramsau b.Berchtesgaden",
    "Redwitz a.d.Rodach",
    "Rettenbach a.Auerberg",
    "Reuth b.Erbendorf",
    "Rohr i.NB",
    "Röthenbach a.d.Pegnitz",
    "Rott a.Inn",
    "Rottenburg a.d.Laaber",
    "Ruhstorf a.d.Rott",
    "Saal a.d.Donau",
    "Saal a.d.Saale",
    "Sachsen b.Ansbach",
    "Sand a.Main",
    "Schönau a.d.Brend",
    "Schönau a.Königssee",
    "Schönbrunn i.Steigerwald",
    "Schondorf a.Ammersee",
    "Schwaig b.Nürnberg",
    "Schwarzach a.Main",
    "Schwarzach b.Nabburg",
    "Schwarzenbach a.d.Saale",
    "Schwarzenbach a.Wald",
    "Seehausen a.Staffelsee",
    "Seubersdorf i.d.OPf.",
    "Simbach a.Inn",
    "Sondheim v.d.Rhön",
    "Steinbach a.Wald",
    "Stockstadt a.Main",
    "Stötten a.Auerberg",
    "Sulzbach a.Main",
    "Sulzdorf a.d.Lederhecke",
    "Sulzfeld a.Main",
    "Taching a.See",
    "Thundorf i.UFr.",
    "Töging a.Inn",
    "Uffing a.Staffelsee",
    "Utting a.Ammersee",
    "Vohburg a.d.Donau",
    "Waging a.See",
    "Wasserburg a.Inn",
    "Weiden i.d.OPf.",
    "Weidhausen b.Coburg",
    "Weilheim i.OB",
    "Weißenburg i.Bay.",
    "Wörth a.d.Donau",
    "Wörth a.d.Isar",
    "Wörth a.Main",
    "Wülfershausen a.d.Saale",
    "Zeil a.Main",
    "Zell a.Main",
    "Aalen",
    "Achern",
    "Albstadt",
    "Backnang",
    "Bad Mergentheim",
    "Bad Rappenau",
    "Balingen",
    "Biberach an der Riß",
    "Bietigheim-Bissingen",
    "Böblingen",
    "Bretten",
    "Bruchsal",
    "Bühl",
    "Calw",
    "Crailsheim",
    "Ditzingen",
    "Donaueschingen",
    "Ehingen (Donau)",
    "Eislingen/Fils",
    "Ellwangen (Jagst)",
    "Emmendingen",
    "Eppingen",
    "Esslingen am Neckar",
    "Ettlingen",
    "Fellbach",
    "Filderstadt",
    "Freudenstadt",
    "Friedrichshafen",
    "Gaggenau",
    "Geislingen an der Steige",
    "Giengen an der Brenz",
    "Göppingen",
    "Heidenheim an der Brenz",
    "Herrenberg",
    "Hockenheim",
    "Horb am Neckar",
    "Kehl",
    "Kirchheim unter Teck",
    "Konstanz",
    "Kornwestheim",
    "Lahr/Schwarzwald",
    "Laupheim",
    "Leimen",
    "Leinfelden-Echterdingen",
    "Leonberg",
    "Leutkirch im Allgäu",
    "Lörrach",
    "Ludwigsburg",
    "Metzingen",
    "Mosbach",
    "Mössingen",
    "Mühlacker",
    "Nagold",
    "Neckarsulm",
    "Nürtingen",
    "Oberkirch",
    "Offenburg",
    "Öhringen",
    "Ostfildern",
    "Radolfzell am Bodensee",
    "Rastatt",
    "Ravensburg",
    "Remseck am Neckar",
    "Reutlingen",
    "Rheinfelden (Baden)",
    "Rheinstetten",
    "Rottenburg am Neckar",
    "Rottweil",
    "Schorndorf",
    "Schramberg",
    "Schwäbisch Gmünd",
    "Schwäbisch Hall",
    "Schwetzingen",
    "Sindelfingen",
    "Singen (Hohentwiel)",
    "Sinsheim",
    "Stutensee",
    "Tübingen",
    "Tuttlingen",
    "Überlingen",
    "Vaihingen an der Enz",
    "Villingen-Schwenningen",
    "Waghäusel",
    "Waiblingen",
    "Waldkirch",
    "Waldshut-Tiengen",
    "Wangen im Allgäu",
    "Weil am Rhein",
    "Weingarten",
    "Weinheim",
    "Weinstadt",
    "Wertheim",
    "Wiesloch",
    "Winnenden",
    "Aach",
    "Aalen",
    "Abstatt",
    "Abtsgmünd",
    "Achberg",
    "Achern",
    "Achstetten",
    "Adelberg",
    "Adelmannsfelden",
    "Adelsheim",
    "Affalterbach",
    "Aglasterhausen",
    "Ahorn",
    "Aichelberg",
    "Aichhalden",
    "Aichstetten",
    "Aichtal",
    "Aichwald",
    "Aidlingen",
    "Aitern",
    "Aitrach",
    "Albbruck",
    "Albershausen",
    "Albstadt",
    "Aldingen",
    "Alfdorf",
    "Allensbach",
    "Alleshausen",
    "Allmannsweiler",
    "Allmendingen",
    "Allmersbach im Tal",
    "Alpirsbach",
    "Altbach",
    "Altdorf (Lkr. Böblingen)",
    "Altdorf (Lkr. Esslingen)",
    "Altenriet",
    "Altensteig",
    "Altheim (Alb)",
    "Altheim (Alb-Donau-Kreis)",
    "Altheim (Lkr. Biberach)",
    "Althengstett",
    "Althütte",
    "Altlußheim",
    "Altshausen",
    "Ammerbuch",
    "Amstetten",
    "Amtzell",
    "Angelbachtal",
    "Appenweier",
    "Argenbühl",
    "Aspach",
    "Asperg",
    "Assamstadt",
    "Asselfingen",
    "Attenweiler",
    "Au (Breisgau)",
    "Au am Rhein",
    "Auenwald",
    "Auggen",
    "Aulendorf",
    "Backnang",
    "Bad Bellingen",
    "Bad Boll",
    "Bad Buchau",
    "Bad Ditzenbach",
    "Bad Dürrheim",
    "Baden-Baden",
    "Badenweiler",
    "Bad Friedrichshall",
    "Bad Herrenalb",
    "Bad Krozingen",
    "Bad Liebenzell",
    "Bad Mergentheim",
    "Bad Peterstal-Griesbach",
    "Bad Rappenau",
    "Bad Rippoldsau-Schapbach",
    "Bad Säckingen",
    "Bad Saulgau",
    "Bad Schönborn",
    "Bad Schussenried",
    "Bad Teinach-Zavelstein",
    "Bad Überkingen",
    "Bad Urach",
    "Bad Waldsee",
    "Bad Wildbad",
    "Bad Wimpfen",
    "Bad Wurzach",
    "Bahlingen am Kaiserstuhl",
    "Baienfurt",
    "Baiersbronn",
    "Baindt",
    "Balgheim",
    "Balingen",
    "Ballendorf",
    "Ballrechten-Dottingen",
    "Baltmannsweiler",
    "Balzheim",
    "Bammental",
    "Bärenthal",
    "Bartholomä",
    "Beilstein",
    "Beimerstetten",
    "Bempflingen",
    "Benningen am Neckar",
    "Berg",
    "Bergatreute",
    "Berghaupten",
    "Berghülen",
    "Berglen",
    "Berkheim",
    "Bermatingen",
    "Bernau im Schwarzwald",
    "Bernstadt",
    "Besigheim",
    "Betzenweiler",
    "Beuren",
    "Beuron",
    "Biberach (Baden)",
    "Biberach an der Riß",
    "Biederbach",
    "Bietigheim (Baden)",
    "Bietigheim-Bissingen",
    "Billigheim",
    "Binau",
    "Bingen",
    "Binzen",
    "Birenbach",
    "Birkenfeld",
    "Bischweier",
    "Bisingen",
    "Bissingen an der Teck",
    "Bitz",
    "Blaubeuren",
    "Blaufelden",
    "Blaustein",
    "Blumberg",
    "Böbingen an der Rems",
    "Böblingen",
    "Bodelshausen",
    "Bodman-Ludwigshafen",
    "Bodnegg",
    "Böhmenkirch",
    "Böllen",
    "Bollschweil",
    "Boms",
    "Bondorf",
    "Bonndorf im Schwarzwald",
    "Bönnigheim",
    "Bopfingen",
    "Börslingen",
    "Börtlingen",
    "Bösingen",
    "Böttingen",
    "Bötzingen",
    "Boxberg",
    "Brackenheim",
    "Bräunlingen",
    "Braunsbach",
    "Breisach am Rhein",
    "Breitingen",
    "Breitnau",
    "Bretten",
    "Bretzfeld",
    "Brigachtal",
    "Bruchsal",
    "Brühl",
    "Bubsheim",
    "Buchen (Odenwald)",
    "Buchenbach",
    "Buchheim",
    "Buggingen",
    "Bühl",
    "Bühlertal",
    "Bühlertann",
    "Bühlerzell",
    "Burgrieden",
    "Burgstetten",
    "Burladingen",
    "Büsingen am Hochrhein",
    "Calw",
    "Cleebronn",
    "Crailsheim",
    "Creglingen",
    "Dachsberg (Südschwarzwald)",
    "Daisendorf",
    "Dauchingen",
    "Dautmergen",
    "Deckenpfronn",
    "Deggenhausertal",
    "Deggingen",
    "Deilingen",
    "Deißlingen",
    "Deizisau",
    "Denkendorf",
    "Denkingen",
    "Denzlingen",
    "Dettenhausen",
    "Dettenheim",
    "Dettighofen",
    "Dettingen an der Erms",
    "Dettingen an der Iller",
    "Dettingen unter Teck",
    "Dielheim",
    "Dietenheim",
    "Dietingen",
    "Dischingen",
    "Ditzingen",
    "Dobel",
    "Dogern",
    "Donaueschingen",
    "Donzdorf",
    "Dormettingen",
    "Dornhan",
    "Dornstadt",
    "Dornstetten",
    "Dörzbach",
    "Dossenheim",
    "Dotternhausen",
    "Drackenstein",
    "Dunningen",
    "Durbach",
    "Dürbheim",
    "Durchhausen",
    "Durlangen",
    "Dürmentingen",
    "Durmersheim",
    "Dürnau (Lkr. Göppingen)",
    "Dürnau (Lkr. Biberach)",
    "Dußlingen",
    "Ebenweiler",
    "Eberbach",
    "Eberdingen",
    "Eberhardzell",
    "Ebersbach an der Fils",
    "Ebersbach-Musbach",
    "Eberstadt",
    "Ebhausen",
    "Ebringen",
    "Edingen-Neckarhausen",
    "Efringen-Kirchen",
    "Egenhausen",
    "Egesheim",
    "Eggenstein-Leopoldshafen",
    "Eggingen",
    "Ehingen (Donau)",
    "Ehningen",
    "Ehrenkirchen",
    "Eichstegen",
    "Eichstetten am Kaiserstuhl",
    "Eigeltingen",
    "Eimeldingen",
    "Eisenbach (Hochschwarzwald)",
    "Eisingen",
    "Eislingen/Fils",
    "Elchesheim-Illingen",
    "Ellenberg",
    "Ellhofen",
    "Ellwangen (Jagst)",
    "Elzach",
    "Elztal",
    "Emeringen",
    "Emerkingen",
    "Emmendingen",
    "Emmingen-Liptingen",
    "Empfingen",
    "Endingen am Kaiserstuhl",
    "Engelsbrand",
    "Engen",
    "Engstingen",
    "Eningen unter Achalm",
    "Enzklösterle",
    "Epfenbach",
    "Epfendorf",
    "Eppelheim",
    "Eppingen",
    "Erbach",
    "Erdmannhausen",
    "Eriskirch",
    "Erkenbrechtsweiler",
    "Erlenbach",
    "Erlenmoos",
    "Erligheim",
    "Erolzheim",
    "Ertingen",
    "Eschach",
    "Eschbach",
    "Eschbronn",
    "Eschelbronn",
    "Eschenbach",
    "Essingen",
    "Esslingen am Neckar",
    "Ettenheim",
    "Ettlingen",
    "Eutingen im Gäu",
    "Fahrenbach",
    "Feldberg (Schwarzwald)",
    "Fellbach",
    "Fichtenau",
    "Fichtenberg",
    "Filderstadt",
    "Fischerbach",
    "Fischingen",
    "Flein",
    "Fleischwangen",
    "Fluorn-Winzeln",
    "Forbach",
    "Forchheim",
    "Forchtenberg",
    "Forst",
    "Frankenhardt",
    "Freiamt",
    "Freiberg am Neckar",
    "Freiburg im Breisgau",
    "Freudenberg",
    "Freudenstadt",
    "Freudental",
    "Frickenhausen",
    "Frickingen",
    "Fridingen an der Donau",
    "Friedenweiler",
    "Friedrichshafen",
    "Friesenheim",
    "Friolzheim",
    "Frittlingen",
    "Fröhnd",
    "Fronreute",
    "Furtwangen im Schwarzwald",
    "Gaggenau",
    "Gaiberg",
    "Gaienhofen",
    "Gaildorf",
    "Gailingen am Hochrhein",
    "Gammelshausen",
    "Gammertingen",
    "Gärtringen",
    "Gäufelden",
    "Gechingen",
    "Geisingen",
    "Geislingen (b. Balingen)",
    "Geislingen an der Steige",
    "Gemmingen",
    "Gemmrigheim",
    "Gengenbach",
    "Gerabronn",
    "Gerlingen",
    "Gernsbach",
    "Gerstetten",
    "Giengen an der Brenz",
    "Gingen an der Fils",
    "Glatten",
    "Glottertal",
    "Göggingen",
    "Gomadingen",
    "Gomaringen",
    "Gondelsheim",
    "Göppingen",
    "Görwihl",
    "Gosheim",
    "Gottenheim",
    "Gottmadingen",
    "Graben-Neudorf",
    "Grabenstetten",
    "Grafenau",
    "Grafenberg",
    "Grafenhausen",
    "Grenzach-Wyhlen",
    "Griesingen",
    "Grömbach",
    "Großbettlingen",
    "Großbottwar",
    "Grosselfingen",
    "Großerlach",
    "Großrinderfeld",
    "Gruibingen",
    "Grundsheim",
    "Grünkraut",
    "Grünsfeld",
    "Gschwend",
    "Guggenhausen",
    "Güglingen",
    "Gundelfingen",
    "Gundelsheim",
    "Gunningen",
    "Gutach im Breisgau",
    "Gutach (Schwarzwaldbahn)",
    "Gütenbach",
    "Gutenzell-Hürbel",
    "Häg-Ehrsberg",
    "Hagnau am Bodensee",
    "Haigerloch",
    "Haiterbach",
    "Hambrücken",
    "Hardheim",
    "Hardt",
    "Hardthausen am Kocher",
    "Hartheim am Rhein",
    "Hasel",
    "Haslach im Kinzigtal",
    "Haßmersheim",
    "Hattenhofen",
    "Hausach",
    "Hausen am Bussen",
    "Hausen am Tann",
    "Hausen im Wiesental",
    "Hausen ob Verena",
    "Häusern",
    "Hayingen",
    "Hechingen",
    "Heddesbach",
    "Heddesheim",
    "Heidelberg",
    "Heidenheim an der Brenz",
    "Heilbronn",
    "Heiligenberg",
    "Heiligkreuzsteinach",
    "Heimsheim",
    "Heiningen",
    "Heitersheim",
    "Helmstadt-Bargen",
    "Hemmingen",
    "Hemsbach",
    "Herbertingen",
    "Herbolzheim",
    "Herbrechtingen",
    "Herdwangen-Schönach",
    "Hermaringen",
    "Heroldstatt",
    "Herrenberg",
    "Herrischried",
    "Hessigheim",
    "Hettingen",
    "Heubach",
    "Heuchlingen",
    "Heuweiler",
    "Hildrizhausen",
    "Hilzingen",
    "Hinterzarten",
    "Hirrlingen",
    "Hirschberg an der Bergstraße",
    "Hochdorf (Lkr. Esslingen)",
    "Hochdorf (Lkr. Biberach)",
    "Höchenschwand",
    "Hockenheim",
    "Höfen an der Enz",
    "Hofstetten",
    "Hohberg",
    "Hohenfels",
    "Hohenstadt",
    "Hohenstein",
    "Hohentengen",
    "Hohentengen am Hochrhein",
    "Holzgerlingen",
    "Holzkirch",
    "Holzmaden",
    "Höpfingen",
    "Horb am Neckar",
    "Horben",
    "Horgenzell",
    "Hornberg",
    "Hoßkirch",
    "Hüffenhardt",
    "Hüfingen",
    "Hügelsheim",
    "Hülben",
    "Hüttisheim",
    "Hüttlingen",
    "Ibach",
    "Iffezheim",
    "Igersheim",
    "Iggingen",
    "Ihringen",
    "Illerkirchberg",
    "Illerrieden",
    "Illingen",
    "Illmensee",
    "Ilsfeld",
    "Ilshofen",
    "Ilvesheim",
    "Immendingen",
    "Immenstaad am Bodensee",
    "Ingelfingen",
    "Ingersheim",
    "Ingoldingen",
    "Inzigkofen",
    "Inzlingen",
    "Irndorf",
    "Isny im Allgäu",
    "Ispringen",
    "Ittlingen",
    "Jagsthausen",
    "Jagstzell",
    "Jestetten",
    "Jettingen",
    "Jungingen",
    "Kaisersbach",
    "Kämpfelbach",
    "Kandern",
    "Kanzach",
    "Kappel-Grafenhausen",
    "Kappelrodeck",
    "Karlsbad",
    "Karlsdorf-Neuthard",
    "Karlsruhe",
    "Kehl",
    "Keltern",
    "Kenzingen",
    "Kernen im Remstal",
    "Ketsch",
    "Kieselbronn",
    "Kippenheim",
    "Kirchardt",
    "Kirchberg an der Iller",
    "Kirchberg an der Jagst",
    "Kirchberg an der Murr",
    "Kirchdorf an der Iller",
    "Kirchentellinsfurt",
    "Kirchheim am Neckar",
    "Kirchheim am Ries",
    "Kirchheim unter Teck",
    "Kirchzarten",
    "Kißlegg",
    "Kleines Wiesental",
    "Klettgau",
    "Knittlingen",
    "Kohlberg",
    "Kolbingen",
    "Köngen",
    "Königheim",
    "Königsbach-Stein",
    "Königsbronn",
    "Königseggwald",
    "Königsfeld im Schwarzwald",
    "Königsheim",
    "Konstanz",
    "Korb",
    "Korntal-Münchingen",
    "Kornwestheim",
    "Kraichtal",
    "Krauchenwies",
    "Krautheim",
    "Kreßberg",
    "Kressbronn am Bodensee",
    "Kronau",
    "Kuchen",
    "Külsheim",
    "Künzelsau",
    "Kupferzell",
    "Kuppenheim",
    "Kürnbach",
    "Küssaberg",
    "Kusterdingen",
    "Ladenburg",
    "Lahr/Schwarzwald",
    "Laichingen",
    "Langenargen",
    "Langenau",
    "Langenbrettach",
    "Langenburg",
    "Langenenslingen",
    "Lauchheim",
    "Lauchringen",
    "Lauda-Königshofen",
    "Laudenbach",
    "Lauf",
    "Laufenburg (Baden)",
    "Lauffen am Neckar",
    "Laupheim",
    "Lautenbach",
    "Lauterach",
    "Lauterbach",
    "Lauterstein",
    "Lehrensteinsfeld",
    "Leibertingen",
    "Leimen",
    "Leinfelden-Echterdingen",
    "Leingarten",
    "Leinzell",
    "Lenningen",
    "Lenzkirch",
    "Leonberg",
    "Leutenbach",
    "Leutkirch im Allgäu",
    "Lichtenau",
    "Lichtenstein",
    "Lichtenwald",
    "Limbach",
    "Linkenheim-Hochstetten",
    "Lobbach",
    "Löchgau",
    "Loffenau",
    "Löffingen",
    "Lonsee",
    "Lorch",
    "Lörrach",
    "Loßburg",
    "Lottstetten",
    "Löwenstein",
    "Ludwigsburg",
    "Magstadt",
    "Mahlberg",
    "Mahlstetten",
    "Mainhardt",
    "Malsburg-Marzell",
    "Malsch (Lkr. Karlsruhe)",
    "Malsch (Rhein-Neckar-Kreis)",
    "Malterdingen",
    "Mannheim",
    "Marbach am Neckar",
    "March",
    "Markdorf",
    "Markgröningen",
    "Marxzell",
    "Maselheim",
    "Massenbachhausen",
    "Mauer",
    "Maulbronn",
    "Maulburg",
    "Meckenbeuren",
    "Meckesheim",
    "Meersburg",
    "Mehrstetten",
    "Meißenheim",
    "Mengen",
    "Merdingen",
    "Merklingen",
    "Merzhausen",
    "Meßkirch",
    "Meßstetten",
    "Metzingen",
    "Michelbach an der Bilz",
    "Michelfeld",
    "Mietingen",
    "Mittelbiberach",
    "Möckmühl",
    "Mögglingen",
    "Möglingen",
    "Mönchweiler",
    "Mönsheim",
    "Moos",
    "Moosburg",
    "Mosbach",
    "Mössingen",
    "Mötzingen",
    "Mudau",
    "Muggensturm",
    "Mühlacker",
    "Mühlenbach",
    "Mühlhausen (Kraichgau)",
    "Mühlhausen im Täle",
    "Mühlhausen-Ehingen",
    "Mühlheim an der Donau",
    "Mühlingen",
    "Mulfingen",
    "Müllheim",
    "Mundelsheim",
    "Munderkingen",
    "Münsingen",
    "Münstertal/Schwarzwald",
    "Murg",
    "Murr",
    "Murrhardt",
    "Mutlangen",
    "Nagold",
    "Nattheim",
    "Neckarbischofsheim",
    "Neckargemünd",
    "Neckargerach",
    "Neckarsulm",
    "Neckartailfingen",
    "Neckartenzlingen",
    "Neckarwestheim",
    "Neckarzimmern",
    "Neenstetten",
    "Nehren",
    "Neidenstein",
    "Neidlingen",
    "Nellingen",
    "Nerenstetten",
    "Neresheim",
    "Neubulach",
    "Neudenau",
    "Neuenbürg",
    "Neuenburg am Rhein",
    "Neuenstadt am Kocher",
    "Neuenstein",
    "Neuffen",
    "Neufra",
    "Neuhausen (Enzkreis)",
    "Neuhausen auf den Fildern",
    "Neuhausen ob Eck",
    "Neukirch",
    "Neuler",
    "Neulingen",
    "Neulußheim",
    "Neunkirchen",
    "Neuried",
    "Neustetten",
    "Neuweiler",
    "Niedereschach",
    "Niedernhall",
    "Niederstetten",
    "Niederstotzingen",
    "Niefern-Öschelbronn",
    "Nordheim",
    "Nordrach",
    "Notzingen",
    "Nufringen",
    "Nürtingen",
    "Nusplingen",
    "Nußloch",
    "Oberboihingen",
    "Oberderdingen",
    "Oberdischingen",
    "Obergröningen",
    "Oberharmersbach",
    "Oberhausen-Rheinhausen",
    "Oberkirch",
    "Oberkochen",
    "Obermarchtal",
    "Oberndorf am Neckar",
    "Obernheim",
    "Oberreichenbach",
    "Oberried",
    "Oberriexingen",
    "Oberrot",
    "Obersontheim",
    "Oberstadion",
    "Oberstenfeld",
    "Obersulm",
    "Oberteuringen",
    "Oberwolfach",
    "Obrigheim",
    "Ochsenhausen",
    "Oedheim",
    "Offenau",
    "Offenburg",
    "Ofterdingen",
    "Oftersheim",
    "Oggelshausen",
    "Ohlsbach",
    "Ohmden",
    "Öhningen",
    "Öhringen",
    "Ölbronn-Dürrn",
    "Öllingen",
    "Öpfingen",
    "Oppenau",
    "Oppenweiler",
    "Orsingen-Nenzingen",
    "Ortenberg",
    "Ostelsheim",
    "Osterburken",
    "Ostfildern",
    "Ostrach",
    "Östringen",
    "Ötigheim",
    "Ötisheim",
    "Ottenbach",
    "Ottenhöfen im Schwarzwald",
    "Ottersweier",
    "Owen",
    "Owingen",
    "Pfaffenhofen",
    "Pfaffenweiler",
    "Pfalzgrafenweiler",
    "Pfedelbach",
    "Pfinztal",
    "Pforzheim",
    "Pfronstetten",
    "Pfullendorf",
    "Pfullingen",
    "Philippsburg",
    "Plankstadt",
    "Pleidelsheim",
    "Pliezhausen",
    "Plochingen",
    "Plüderhausen",
    "Radolfzell am Bodensee",
    "Rainau",
    "Rammingen",
    "Rangendingen",
    "Rastatt",
    "Ratshausen",
    "Rauenberg",
    "Ravensburg",
    "Ravenstein",
    "Rechberghausen",
    "Rechtenstein",
    "Reichartshausen",
    "Reichenau",
    "Reichenbach an der Fils",
    "Reichenbach am Heuberg",
    "Reilingen",
    "Remchingen",
    "Remseck am Neckar",
    "Remshalden",
    "Renchen",
    "Renningen",
    "Renquishausen",
    "Reute",
    "Reutlingen",
    "Rheinau",
    "Rheinfelden (Baden)",
    "Rheinhausen",
    "Rheinmünster",
    "Rheinstetten",
    "Rickenbach",
    "Riederich",
    "Riedhausen",
    "Riedlingen",
    "Riegel am Kaiserstuhl",
    "Rielasingen-Worblingen",
    "Riesbürg",
    "Rietheim-Weilheim",
    "Ringsheim",
    "Rohrdorf",
    "Roigheim",
    "Römerstein",
    "Rosenberg (Baden)",
    "Rosenberg (Württemberg)",
    "Rosenfeld",
    "Rosengarten",
    "Rot am See",
    "Rot an der Rot",
    "Rottenacker",
    "Rottenburg am Neckar",
    "Rottweil",
    "Rudersberg",
    "Rümmingen",
    "Ruppertshofen",
    "Rust",
    "Rutesheim",
    "Sachsenheim",
    "Salach",
    "Salem",
    "Sandhausen",
    "Sasbach (Ortenau)",
    "Sasbach am Kaiserstuhl",
    "Sasbachwalden",
    "Satteldorf",
    "Sauldorf",
    "Schallbach",
    "Schallstadt",
    "Schechingen",
    "Scheer",
    "Schefflenz",
    "Schelklingen",
    "Schemmerhofen",
    "Schenkenzell",
    "Schiltach",
    "Schlaitdorf",
    "Schlat",
    "Schliengen",
    "Schlier",
    "Schlierbach",
    "Schluchsee",
    "Schnürpflingen",
    "Schömberg (b. Balingen)",
    "Schömberg (Lkr. Calw)",
    "Schonach im Schwarzwald",
    "Schönaich",
    "Schönau (Odenwald)",
    "Schönau im Schwarzwald",
    "Schönbrunn",
    "Schönenberg",
    "Schöntal",
    "Schönwald im Schwarzwald",
    "Schopfheim",
    "Schopfloch",
    "Schorndorf",
    "Schramberg",
    "Schriesheim",
    "Schrozberg",
    "Schuttertal",
    "Schutterwald",
    "Schwäbisch Gmünd",
    "Schwäbisch Hall",
    "Schwaigern",
    "Schwaikheim",
    "Schwanau",
    "Schwarzach",
    "Schwendi",
    "Schwenningen",
    "Schwetzingen",
    "Schwieberdingen",
    "Schwörstadt",
    "Seckach",
    "Seebach",
    "Seekirch",
    "Seelbach",
    "Seewald",
    "Seitingen-Oberflacht",
    "Sersheim",
    "Setzingen",
    "Sexau",
    "Siegelsbach",
    "Sigmaringen",
    "Sigmaringendorf",
    "Simmersfeld",
    "Simmozheim",
    "Simonswald",
    "Sindelfingen",
    "Singen (Hohentwiel)",
    "Sinsheim",
    "Sinzheim",
    "Sipplingen",
    "Sölden",
    "Sonnenbühl",
    "Sontheim an der Brenz",
    "Spaichingen",
    "Spechbach",
    "Spiegelberg",
    "Spraitbach",
    "St. Blasien",
    "St. Georgen im Schwarzwald",
    "St. Johann",
    "St. Leon-Rot",
    "St. Märgen",
    "St. Peter",
    "Staig",
    "Starzach",
    "Staufen im Breisgau",
    "Stegen",
    "Steinach",
    "Steinen",
    "Steinenbronn",
    "Steinhausen an der Rottum",
    "Steinheim am Albuch",
    "Steinheim an der Murr",
    "Steinmauern",
    "Steißlingen",
    "Sternenfels",
    "Stetten (Bodenseekreis)",
    "Stetten am kalten Markt",
    "Stimpfach",
    "Stockach",
    "Stödtlen",
    "Straßberg",
    "Straubenhardt",
    "Stühlingen",
    "Stutensee",
    "Stuttgart (Landeshauptstadt)",
    "Sulz am Neckar",
    "Sulzbach an der Murr",
    "Sulzbach-Laufen",
    "Sulzburg",
    "Sulzfeld",
    "Süßen",
    "Täferrot",
    "Talheim (Lkr. Heilbronn)",
    "Talheim (Lkr. Tuttlingen)",
    "Tamm",
    "Tannhausen",
    "Tannheim",
    "Tauberbischofsheim",
    "Tengen",
    "Teningen",
    "Tettnang",
    "Tiefenbach",
    "Tiefenbronn",
    "Titisee-Neustadt",
    "Todtmoos",
    "Todtnau",
    "Triberg im Schwarzwald",
    "Trochtelfingen",
    "Trossingen",
    "Tübingen",
    "Tunau",
    "Tuningen",
    "Tuttlingen",
    "Überlingen",
    "Ubstadt-Weiher",
    "Uhingen",
    "Uhldingen-Mühlhofen",
    "Ühlingen-Birkendorf",
    "Ulm",
    "Umkirch",
    "Ummendorf",
    "Unlingen",
    "Untereisesheim",
    "Unterensingen",
    "Untergruppenbach",
    "Unterkirnach",
    "Untermarchtal",
    "Untermünkheim",
    "Unterreichenbach",
    "Unterschneidheim",
    "Unterstadion",
    "Unterwachingen",
    "Unterwaldhausen",
    "Urbach",
    "Uttenweiler",
    "Utzenfeld",
    "Vaihingen an der Enz",
    "Vellberg",
    "Veringenstadt",
    "Villingendorf",
    "Villingen-Schwenningen",
    "Vogt",
    "Vogtsburg im Kaiserstuhl",
    "Vöhrenbach",
    "Vöhringen",
    "Volkertshausen",
    "Vörstetten",
    "Waghäusel",
    "Waiblingen",
    "Waibstadt",
    "Wain",
    "Wald",
    "Waldachtal",
    "Waldbronn",
    "Waldbrunn",
    "Waldburg",
    "Walddorfhäslach",
    "Waldenbuch",
    "Waldenburg",
    "Waldkirch",
    "Waldshut-Tiengen",
    "Waldstetten",
    "Walheim",
    "Walldorf",
    "Walldürn",
    "Wallhausen",
    "Walzbachtal",
    "Wangen (b. Göppingen)",
    "Wangen im Allgäu",
    "Wannweil",
    "Warthausen",
    "Wäschenbeuren",
    "Wehingen",
    "Wehr",
    "Weidenstetten",
    "Weikersheim",
    "Weil am Rhein",
    "Weil der Stadt",
    "Weil im Schönbuch",
    "Weilen unter den Rinnen",
    "Weilheim (Baden)",
    "Weilheim an der Teck",
    "Weingarten (Baden)",
    "Weingarten",
    "Weinheim",
    "Weinsberg",
    "Weinstadt",
    "Weisenbach",
    "Weissach (Lkr. Böblingen)",
    "Weissach im Tal",
    "Weißbach",
    "Weisweil",
    "Wellendingen",
    "Welzheim",
    "Wembach",
    "Wendlingen am Neckar",
    "Wernau",
    "Werbach",
    "Wertheim",
    "Westerheim",
    "Westerstetten",
    "Westhausen",
    "Widdern",
    "Wieden",
    "Wiernsheim",
    "Wiesenbach",
    "Wiesensteig",
    "Hamburg",
    "Bremen",
    "Frankfurt",
    "Leipzig",
    "Wimsheim",
    "Winden im Elztal",
    "Winnenden",
    "Winterbach",
    "Winterlingen",
    "Wittighausen",
    "Wittlingen",
    "Wittnau",
    "Wolfach",
    "Wolfegg",
    "Wolfschlugen",
    "Wolpertshausen",
    "Wolpertswende",
    "Wörnersberg",
    "Wört",
    "Wurmberg",
    "Wurmlingen",
    "Wüstenrot",
    "Wutach",
    "Wutöschingen",
    "Wyhl am Kaiserstuhl",
]

# location_list = location_list[:99]
# Current Date of Ad when it was created till today
# standard_date = datetime.datetime.strptime(filter_date, "%d.%m.%Y").date()

base_path = os.path.dirname(os.path.abspath(__file__))
config_path = os.path.join(os.path.dirname(os.path.dirname(base_path)), "db_config.json")

# read db config
config = json.load(open(config_path))

# connect to db
mydb = mysql.connector.connect(
    host = config["host"],
    user = config["user"],
    password = config["password"],
    port = config["port"],
    database = config["database"],
)

mycursor = mydb.cursor(buffered=True)
## special values from db
special_strs = []
db2 = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = '',
    port = 3306,
    database = 'mobilecrawler',
)
cursor2 = db2.cursor()
load_special_query = 'select * from specials'
cursor2.execute(load_special_query)
special_strs = cursor2.fetchall()
cursor2.close()
db2.close()

def is_in(str, pattern):
    return (1 if (' '+pattern.upper() in str.upper() or '"'+pattern.upper() in str.upper()) else 0 )

def check_special_from_title(title):
    for name in special_strs:
        if is_in(title, name[1]):
            return name[1]
    return None

old_records = []
def process_product_db(item):
    print('processing product data..........................')
    try:
        try:
            if item["Kilometerstand"]:
                item["Kilometerstand"] = re.search(r"\d+", item["Kilometerstand"].replace(".", "").split(",")[0]).group()
        except:
            pass

        try:
            if item["Leistung"]:
                power = item["Leistung"]
                if re.search(r"\d+\s*KW", power, re.I):
                    power = round(int(re.search(r"(\d+)\s*KW", power, re.I).groups()[0]) / 0.735499)
                elif re.search(r"\d+\s*PS", power, re.I):
                    power = re.search(r"(\d+)\s*PS", power, re.I).groups()[0]
                elif re.search(r"\d+", power):
                    power = re.search(r"\d+", power).group()
                else:
                    power = 0

                item["Leistung"] = power
        except:
            pass

        try:
            if item["Erstzulassung"]:
                register_date = item["Erstzulassung"]
                register_date = re.search(r"\d+", register_date).group()[:4]
                item["Erstzulassung"] = register_date
        except:
            pass

        try:
            if item["Getriebe"]:
                gearbox = item["Getriebe"]
                if "Schaltung" in gearbox or "Manuell" in gearbox:
                    gearbox = "Schaltung"
                # elif "Manuell" in gearbox:
                #     gearbox = 
                # else:
                #     gearbox = 
                item["Getriebe"] = gearbox

        except:
            pass
        
        print(item)

        # check batch_id
        batch_existing_query = "SELECT batch_id FROM auction_batch WHERE country_id='de'"
        mycursor.execute(batch_existing_query)
        batch_result = mycursor.fetchone()
        batch_id = None
        if batch_result:
            batch_id = batch_result[0]
        if not batch_id:
            # insert to `auction_batch` db.
            batch_insert_query = "INSERT INTO auction_batch (note, country_id) VALUES (%s, %s)"
            batch_insert_value = ("", "de")
            mycursor.execute(batch_insert_query, batch_insert_value)
            mydb.commit()
            batch_id = mycursor.lastrowid

        # check fuel_id
        fuel_existing_query = f"SELECT id FROM mobilecrawler.fuel WHERE name='{item['Kraftstoffart']}'"
        mycursor.execute(fuel_existing_query)
        fuel_result = mycursor.fetchone()

        if fuel_result:
            fuel_id = fuel_result[0]
        else:
            fuel_id = 0

        # check gearbox_id
        gearbox_existing_query = f"SELECT id FROM mobilecrawler.gearbox WHERE name='{item['Getriebe']}'"
        mycursor.execute(gearbox_existing_query)
        gearbox_result = mycursor.fetchone()

        if gearbox_result:
            gearbox_id = gearbox_result[0]
        else:
            gearbox_id = 0

        # check brand id
        brand_id = None
        model_id = None
        print(item['Marke'], item['Modell'])
        brand_existing_query = f"SELECT brand_id FROM mobilecrawler.result WHERE brand_name='{item['Marke']}'"
        mycursor.execute(brand_existing_query)
        brand_result = mycursor.fetchone()

        if brand_result:
            brand_id = brand_result[0]
        # else:
        #     if item["Marke"] == '':
        #         brand_id = None
        #     else:
        #         #insert new brand to mobilecrawler brand table
        #         # max_brand_id_query = f"SELECT MAX(brand_id) FROM mobilecrawler.brand"
        #         # mycursor.execute(max_brand_id_query, multi=True)
        #         # max_id_result = mycursor.fetchone()
        #         # max_brand_id = max_id_result[0] + 1
        #         # #insert new brand name and id
        #         # mycursor.execute("INSERT INTO mobilecrawler.brand (brand_id, brand_name) VALUES (%s,%s)", (max_brand_id, item['Marke']))
        #         # mydb.commit()
        #         # brand_id = max_brand_id

        # check model_id
        if brand_id != None:
            model_existing_query = f"SELECT model_id FROM mobilecrawler.result WHERE model_name='{item['Modell']}' and brand_id={brand_id}"
            mycursor.execute(model_existing_query)
            model_result = mycursor.fetchone()
            
            if model_result:
                model_id = model_result[0]
            else:
                if item["Modell"] == '':
                    model_id = 0
                else:
                    #insert new model to mobilecrawler model table
                    max_model_id_query = f"SELECT MAX(model_id) FROM mobilecrawler.result"
                    mycursor.execute(max_model_id_query)
                    max_id_result = mycursor.fetchone()
                    max_model_id = max_id_result[0] + 1
                    # insert new brand name and id
                    mycursor.execute("INSERT INTO mobilecrawler.result (model_id, model_name, brand_id, brand_name) VALUES (%s,%s,%s,%s)", (max_model_id, item['Modell'], brand_id, item['Marke']))
                    mydb.commit()
                    model_id = max_model_id

        # insert to `auction` table.
        print('Inserting new row into DB.......................')
        try:
            auction_insert_query = "INSERT INTO auction (title, special, end_date, price, mileage, first_registration, power, fuel, gearbox, batch_id, car_brand, car_model, link, size, heating, panoramic_roof, navigation, leather) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
            action_insert_value = (item["Title"], item["Special"], item["Date"], item["Price"], item["Kilometerstand"], item["Erstzulassung"], item["Leistung"], fuel_id, gearbox_id, batch_id, brand_id, model_id, item["Link"], item["Fahrzeugtyp"], item["Standheizung"], item["Schiebedach"], item["Navi"], item["Leder"])
            mycursor.execute(auction_insert_query, action_insert_value)
            mydb.commit()

            auction_id = mycursor.lastrowid
            print('*************************New Row inserted: ', auction_id)
        except Exception as ex:
            print(ex)
        # insert to `history` table.
        # history_insert_query = "INSERT INTO auction_history (end_date, price, mileage, fuel, gearbox) VALUES (%s, %s, %s, %s, %s)"
        # action_insert_value = (item["Date"], item["Price"], item["Kilometerstand"], fuel_id, gearbox_id)
        # mycursor.execute(history_insert_query, action_insert_value)
        # mydb.commit()
    except Exception as e:
        print(e)
        traceback.print_exc()
        pass



class KleinanzeigenSautoSpider(scrapy.Spider):
    name = 'kleinanzeigenSautoSpider'
    allowed_domains = ['ebay-kleinanzeigen.de']
    current_id = 0
    custom_settings = {
        'DOWNLOAD_DELAY': 2,
    }

    def start_requests(self):
        headers = {
            'authority': 'www.ebay-kleinanzeigen.de',
            'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
            'accept': '*/*',
            'sec-ch-ua-mobile': '?0',
            'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36',
            'x-requested-with': 'XMLHttpRequest',
            'sec-fetch-site': 'same-origin',
            'sec-fetch-mode': 'cors',
            'sec-fetch-dest': 'empty',
            'referer': 'https://www.ebay-kleinanzeigen.de',
            'accept-language': 'en-US,en;q=0.9,ko;q=0.8,pt;q=0.7',
        }
        # check old records whether it is available or not.
        old_records_select_query = 'SELECT * FROM auction ORDER BY auction_id'
        mycursor.execute(old_records_select_query)
        old_result = mycursor.fetchall()

        print("Checking Old data.....")
        for row in old_result:
            self.current_id = row[4]
            if row[26] == 1:
                yield scrapy.Request(row[25], meta={'handle_httpstatus_list': [301]}, callback=self.parse_check_availability, headers = headers)
        # scrape new data
        print("Scraping new data.....")
        # yield scrapy.Request('https://www.ebay-kleinanzeigen.de/s-autos/c216', callback=self.parse_csrf, headers=headers)
        yield scrapy.Request('https://www.ebay-kleinanzeigen.de/s-autos/anbieter:privat/anzeige:angebote/c216+autos.schaden_s:nein', callback=self.parse_csrf, headers=headers)
    
    def parse_csrf(self, response):
        csrf = response.xpath("//meta[@name='_csrf']//@content").get()
        headers = {
            'authority': 'www.ebay-kleinanzeigen.de',
            'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
            'accept': '*/*',
            'x-csrf-token': csrf,
            'sec-ch-ua-mobile': '?0',
            'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36',
            'x-requested-with': 'XMLHttpRequest',
            'sec-fetch-site': 'same-origin',
            'sec-fetch-mode': 'cors',
            'sec-fetch-dest': 'empty',
            # 'referer': 'https://www.ebay-kleinanzeigen.de/s-autos/c216',
            'referer': 'https://www.ebay-kleinanzeigen.de/s-autos/anbieter:privat/anzeige:angebote/c216+autos.schaden_s:nein',
            'accept-language': 'en-US,en;q=0.9,ko;q=0.8,pt;q=0.7',
        }
        for location in location_list:
            yield scrapy.Request(f'https://www.ebay-kleinanzeigen.de/s-ort-empfehlungen.json?query={location}', callback=self.parse_url, headers=headers, meta={"location":location})

    def parse_url(self, response):
        
        for key, value in response.json().items():
            # yield scrapy.Request(f'https://www.ebay-kleinanzeigen.de/s-autos/{response.meta["location"]}/c216l{key.replace("_", "")}', callback=self.parse_inventory, meta={"count": 1})
            yield scrapy.Request(f'https://www.ebay-kleinanzeigen.de/s-autos/{response.meta["location"]}/anbieter:privat/anzeige:angebote/c216l{key.replace("_", "")}+autos.schaden_s:nein', callback=self.parse_inventory, meta={"count": 1})
            break

    def parse_inventory(self, response):
        base_product = {
            "Title" : "",
            "Special" : None,
            "Length" : 0,
            "Location" : "",
            "Price" : 0,
            "Date" : datetime.datetime(1, 1, 1, 0, 0),
            "Marke": "",
            "Modell": "",
            "Kilometerstand": 0,
            "Erstzulassung": "",
            "Kraftstoffart": "",
            "Leistung": 0,
            "Getriebe": "",
            "Fahrzeugtyp": "",
            "Material Innenausstattung": "",
            "Link" : "",
            "Standheizung": 0,
            "Schiebedach": 0,
            "Navi": 0,
            "Leder": 0
        }

        if "<body></body>" in response.text:
            if response.meta["count"] < 3:
                yield scrapy.Request(response.url, callback=self.parse_inventory, dont_filter=True, meta={"count": response.meta["count"]+1})
                return

        for product_item in response.xpath("//article[@class='aditem']"):
            try:
                product = base_product.copy()
                product["Title"] = product_item.xpath(".//div[@class='aditem-main--middle']/h2/a[@name]//text()").get().strip()
                product["Special"] = check_special_from_title(product["Title"])
                location = "".join(product_item.xpath(".//div[@class='aditem-main--top--left']//text()").extract())
                if location:
                    product["Location"] = location.strip()
                product_date = "".join(product_item.xpath(".//div[@class='aditem-main--top--right']//text()").extract())
                if product_date:
                    if "Heute" in product_date:
                        _product_date = datetime.date.today()
                    elif "Gestern" in product_date:
                        _product_date = datetime.date.today() - datetime.timedelta(days=1)
                    else:
                        _product_date = datetime.datetime.strptime(product_date.strip(), "%d.%m.%Y").date()
                    product["Date"] = _product_date
                price = product_item.xpath(".//div[@class='aditem-main--middle']/p[@class='aditem-main--middle--price']//text()").get()
                if price:
                    price = re.search(r"\d+", price.replace(".", "").split(",")[0]).group()
                    product["Price"] = price.strip()
                product_link = product_item.xpath(".//div[@class='aditem-main--middle']/h2/a[@name]/@href").get()
                if product_link:
                    product["Link"] = "https://www.ebay-kleinanzeigen.de" + product_link.strip()

                if product["Title"] and product["Link"]:
                    product["Length"] = len(product["Title"])
                    yield scrapy.Request(product["Link"], callback=self.parse_item, meta={"product": product, "count": 1})
            except Exception as e:
                print('An expception occured:')
                print(e)
                continue
        
        next_url = response.xpath("//a[@class='pagination-next']/@href").get()
        if next_url:
            yield response.follow(next_url.strip(), callback=self.parse_inventory, meta={"count": 1})

    def parse_item(self, response):
        print('Parsing item from response data..........................')
        product = response.meta["product"]
        print(product)
        try:
            if "<body></body>" in response.text:
                if response.meta["count"] < 4:
                    yield scrapy.Request(response.url, callback=self.parse_item, dont_filter=True, meta={"count": response.meta["count"]+1, "product":product})
                    return
                else:
                    return

            try:
                if "..." in product["Title"]:
                    product["Title"] = response.xpath("//h1[@id='viewad-title']//text()").get().strip()
                    product["Special"] = check_special_from_title(product["Title"])
            except:
                pass
            
            for attr_ele in response.xpath("//ul[@class='addetailslist']//li"):
                try:
                    attr_list = attr_ele.xpath(".//text()").extract()
                    key = attr_list[0].strip()
                    if "Material" in key:
                        if "Stoff" in attr_list[1].strip():
                            product["Leder"] = 0
                        else:
                            product["Leder"] = 1
                    if key in product:
                        product[key] = attr_list[1].strip()
                except:
                    continue

            
            for attr_ele in response.xpath("//ul[@class='checktaglist']//li"):
                try:
                    val = attr_ele.xpath(".//text()").get()
                    if "Navigations" in val:
                        product["Navi"] = 1
                    elif "Schiebedach" in val:
                        product["Schiebedach"] = 1
                except:
                    continue

            description = "".join(response.xpath("//div[@id='viewad-description']//text()").extract())
            if "Standheizung" in description:
                product["Standheizung"] = 1

            process_product_db(product)
        except Exception as e:
            print(e)
            pass
    def parse_check_availability(self, response):
        statement = response.url.split('/')[-1]
        if 'DELETED_AD' in statement or response.status == 301:
            # change 'is_available' to 0
            old_record_update_query = 'UPDATE auction SET is_available = 0 WHERE auction_id = ' + str(self.current_id)
            print(old_record_update_query)
            mycursor.execute(old_record_update_query)
            mydb.commit()

